using RE4_PS2_MOD_WORKSPACE.Core.Visual;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed class CamTimelineControl:Control
{
    private IReadOnlyList<CamFrame> frames=Array.Empty<CamFrame>();private int selected=-1,anchor=-1;private readonly HashSet<int> selectedFrames=new();
    public event Action<int,IReadOnlyList<int>>? SelectionChanged;public event Action? AddRequested;public event Action? RemoveRequested;
    public CamTimelineControl(){DoubleBuffered=true;Height=88;Dock=DockStyle.Bottom;BackColor=Color.FromArgb(16,20,26);ForeColor=Color.White;Cursor=Cursors.Hand;SetStyle(ControlStyles.ResizeRedraw,true);}
    public void SetFrames(IReadOnlyList<CamFrame>? value,int selectedIndex,bool preserveSelection=false){frames=value??Array.Empty<CamFrame>();selected=frames.Count==0?-1:Math.Clamp(selectedIndex,0,frames.Count-1);if(!preserveSelection){selectedFrames.Clear();if(selected>=0)selectedFrames.Add(selected);anchor=selected;}else{selectedFrames.RemoveWhere(i=>i<0||i>=frames.Count);if(selected>=0)selectedFrames.Add(selected);}Invalidate();}
    protected override void OnPaint(PaintEventArgs e){base.OnPaint(e);Graphics g=e.Graphics;g.SmoothingMode=System.Drawing.Drawing2D.SmoothingMode.AntiAlias;using var line=new Pen(Color.FromArgb(74,86,105),3);using var normal=new SolidBrush(Color.FromArgb(48,58,72));using var multi=new SolidBrush(Color.FromArgb(47,114,168));using var active=new SolidBrush(Color.FromArgb(206,54,62));using var text=new SolidBrush(Color.FromArgb(225,230,238));using var muted=new SolidBrush(Color.FromArgb(145,155,173));using var font=new Font("Segoe UI Semibold",8F);using var small=new Font("Segoe UI",7F);g.DrawString(selectedFrames.Count>1?$"CAM TIMELINE • {selectedFrames.Count} SELECIONADOS":"CAM TIMELINE",font,muted,10,7);DrawButton(g,AddRect(),"+",Color.FromArgb(36,130,92),font);DrawButton(g,RemoveRect(),"−",Color.FromArgb(112,48,55),font);if(frames.Count==0){g.DrawString("Nenhum frame",font,muted,12,44);return;}int left=28,right=Math.Max(left+1,Width-94),y=52;if(frames.Count>1)g.DrawLine(line,left,y,right,y);for(int i=0;i<frames.Count;i++){Point p=FramePoint(i,left,right,y);Brush brush=i==selected?active:selectedFrames.Contains(i)?multi:normal;g.FillEllipse(brush,p.X-10,p.Y-10,20,20);g.DrawString(i.ToString("00"),small,text,p.X-8,p.Y-28);if(selectedFrames.Contains(i))g.DrawEllipse(Pens.White,p.X-12,p.Y-12,24,24);}}
    private static void DrawButton(Graphics g,Rectangle r,string label,Color color,Font font){using var b=new SolidBrush(color);g.FillRectangle(b,r);TextRenderer.DrawText(g,label,font,r,Color.White,TextFormatFlags.HorizontalCenter|TextFormatFlags.VerticalCenter);}
    protected override void OnMouseDown(MouseEventArgs e){base.OnMouseDown(e);if(AddRect().Contains(e.Location)){AddRequested?.Invoke();return;}if(RemoveRect().Contains(e.Location)){RemoveRequested?.Invoke();return;}if(frames.Count==0)return;int left=28,right=Math.Max(left+1,Width-94),best=-1;float distance=18f*18f;for(int i=0;i<frames.Count;i++){Point p=FramePoint(i,left,right,52);float dx=e.X-p.X,dy=e.Y-p.Y,d=dx*dx+dy*dy;if(d<distance){distance=d;best=i;}}if(best<0)return;Keys modifiers=ModifierKeys;if((modifiers&Keys.Shift)!=0&&anchor>=0){selectedFrames.Clear();for(int i=Math.Min(anchor,best);i<=Math.Max(anchor,best);i++)selectedFrames.Add(i);}else if((modifiers&Keys.Control)!=0){if(!selectedFrames.Add(best)&&selectedFrames.Count>1)selectedFrames.Remove(best);anchor=best;}else{selectedFrames.Clear();selectedFrames.Add(best);anchor=best;}selected=best;Invalidate();SelectionChanged?.Invoke(best,selectedFrames.OrderBy(i=>i).ToArray());}
    private Point FramePoint(int index,int left,int right,int y)=>new(frames.Count<=1?(left+right)/2:left+(int)MathF.Round((right-left)*index/(float)(frames.Count-1)),y);
    private Rectangle AddRect()=>new(Math.Max(0,Width-78),8,30,27);private Rectangle RemoveRect()=>new(Math.Max(0,Width-42),8,30,27);
}
