using RE4_PS2_MOD_WORKSPACE.Core.Visual;
using OpenTK.Graphics.OpenGL4;
using NVector3=System.Numerics.Vector3;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed partial class ScenarioViewport
{
    private const float CamWorldScale=.01f;
    private CamScene? camScene;private bool camGpuDirty;
    private int camVao,camVbo,camVertexCount,camSelectedVao,camSelectedVbo,camSelectedVertexCount,camFaceVao,camFaceVbo,camFaceVertexCount,camSelectedFaceVao,camSelectedFaceVbo,camSelectedFaceVertexCount;
    private int camEditVao,camEditVbo,camEditVertexCount,camEditFaceVao,camEditFaceVbo,camEditFaceVertexCount;
    private readonly int[] camGizmoVaos=new int[3],camGizmoVbos=new int[3],camGizmoCounts=new int[3];
    private int selectedCamEntry=-1,selectedCamVertex=-1,selectedCamFace=-1,selectedCamFrame=-1,camDragAxis;private readonly HashSet<int> selectedCamFrames=new();private Dictionary<CamFrame,(NVector3 Position,NVector3 Target)>? camDragFrameGroup;private bool selectedCamTarget;private Point camDragMouse;private List<NVector3>? camDragVertices;private float camDragLower,camDragUpper;private NVector3 camDragPlaneStart,camDragFramePoint;
    private readonly Stack<(Action Undo,Action Redo)> camUndo=new(),camRedo=new();
    private Point camCyclePoint;private int[] camCycleEntries=Array.Empty<int>();private int camCycleIndex=-1;private bool camPointClickConsumed;
    public bool CamVisible{get;set;}=true;public CamScene? CamScene=>camScene;public bool IsCamDragging=>camDragAxis!=0;public CamGizmoMode CamTransformMode{get;set;}=CamGizmoMode.Move;
    public event Action<CamEntry?>? CamEntrySelected;public event Action<CamEntry>? CamEntryEdited;public event Action<int?>? CamVertexSelected;public event Action<int,bool>? CamFrameSelected;public event Action? DeleteCamRequested;
    public void SetCamScene(CamScene? value){camScene=value;selectedCamEntry=-1;selectedCamVertex=selectedCamFace=-1;selectedCamFrames.Clear();camUndo.Clear();camRedo.Clear();ResetCamPickCycle();camGpuDirty=true;Invalidate();}
    public void SelectCamEntry(int fileOrder){if(selectedCamEntry!=fileOrder){selectedCamVertex=selectedCamFace=selectedCamFrame=-1;selectedCamFrames.Clear();selectedCamTarget=false;}selectedCamEntry=fileOrder;camGpuDirty=true;Invalidate();}
    public void SelectCamVertex(int index){selectedCamVertex=index;selectedCamFace=-1;camGpuDirty=true;Invalidate();}
    public void SelectCamFrame(int index,bool targetPoint=false){selectedCamFrame=index;selectedCamFrames.Clear();if(index>=0)selectedCamFrames.Add(index);selectedCamTarget=targetPoint;selectedCamVertex=selectedCamFace=-1;camGpuDirty=true;Invalidate();}
    public void SelectCamFrames(IEnumerable<int> indices,int primary){selectedCamFrames.Clear();foreach(int index in indices)selectedCamFrames.Add(index);selectedCamFrame=primary;selectedCamTarget=false;selectedCamVertex=selectedCamFace=-1;camGpuDirty=true;Invalidate();}
    public void RefreshCamGeometry(){camGpuDirty=true;Invalidate();}
    public bool ConsumeCamPointClick(){bool consumed=camPointClickConsumed;camPointClickConsumed=false;return consumed;}
    private void UploadCam(){camGpuDirty=false;camVertexCount=camSelectedVertexCount=camFaceVertexCount=camSelectedFaceVertexCount=camEditVertexCount=camEditFaceVertexCount=0;if(camScene==null||!glReady)return;EnsureCam(ref camVao,ref camVbo);EnsureCam(ref camSelectedVao,ref camSelectedVbo);EnsureCam(ref camFaceVao,ref camFaceVbo);EnsureCam(ref camSelectedFaceVao,ref camSelectedFaceVbo);EnsureCam(ref camEditVao,ref camEditVbo);EnsureCam(ref camEditFaceVao,ref camEditFaceVbo);for(int i=0;i<3;i++)EnsureCam(ref camGizmoVaos[i],ref camGizmoVbos[i]);var lines=new List<float>();var selectedLines=new List<float>();var faces=new List<float>();var selectedFaces=new List<float>();foreach(CamEntry e in camScene.Entries)AddCamEntry(e,e.FileOrder==selectedCamEntry?selectedLines:lines,e.FileOrder==selectedCamEntry?selectedFaces:faces);UploadLineBuffer(camVao,camVbo,lines,out camVertexCount);UploadLineBuffer(camSelectedVao,camSelectedVbo,selectedLines,out camSelectedVertexCount);UploadLineBuffer(camFaceVao,camFaceVbo,faces,out camFaceVertexCount);UploadLineBuffer(camSelectedFaceVao,camSelectedFaceVbo,selectedFaces,out camSelectedFaceVertexCount);var axes=new[]{new List<float>(),new List<float>(),new List<float>()};var editLines=new List<float>();var editFaces=new List<float>();CamEntry? selected=SelectedCam();if(selected!=null){AddCamEditHandles(axes,editLines,editFaces,selected);bool hasTarget=CamTransformMode!=CamGizmoMode.Vertex||selectedCamVertex>=0&&selectedCamVertex<selected.Vertices.Count;if(hasTarget){NVector3 c=CamGizmoOrigin(selected);float len=CamGizmoLength(selected);bool horizontalFace=CamTransformMode==CamGizmoMode.Face&&selectedCamFace>=selected.Vertices.Count;if(horizontalFace)AddCamArrow(axes[1],c,selectedCamFace==selected.Vertices.Count?-NVector3.UnitY:NVector3.UnitY,len);else{AddCamArrow(axes[0],c,NVector3.UnitX,len);if(CamTransformMode==CamGizmoMode.Move)AddCamArrow(axes[1],c,NVector3.UnitY,len);AddCamArrow(axes[2],c,NVector3.UnitZ,len);}if(CamTransformMode==CamGizmoMode.Scale){CamWorldYRange(selected,out float bottom,out float top);AddCamArrow(axes[1],new NVector3(c.X,bottom,c.Z),-NVector3.UnitY,len*.45f);AddCamArrow(axes[1],new NVector3(c.X,top,c.Z),NVector3.UnitY,len*.45f);}}}UploadLineBuffer(camEditVao,camEditVbo,editLines,out camEditVertexCount);UploadLineBuffer(camEditFaceVao,camEditFaceVbo,editFaces,out camEditFaceVertexCount);for(int i=0;i<3;i++)UploadLineBuffer(camGizmoVaos[i],camGizmoVbos[i],axes[i],out camGizmoCounts[i]);}
    private static void AddCamTrajectory(List<float> lines,CamEntry entry)
    {
        if(entry.Frames.Count<2)return;
        for(int i=1;i<entry.Frames.Count;i++)
        {
            AddCamPathSegment(lines,CamVectorToWorld(entry.Frames[i-1].Position),CamVectorToWorld(entry.Frames[i].Position));
            AddCamPathSegment(lines,CamVectorToWorld(entry.Frames[i-1].Target),CamVectorToWorld(entry.Frames[i].Target));
        }
    }
    private static void AddCamPathSegment(List<float> lines,NVector3 a,NVector3 b)
    {
        AddCamLine(lines,a,b);NVector3 delta=b-a;if(delta.LengthSquared()<.0001f)return;NVector3 direction=NVector3.Normalize(delta);NVector3 side=NVector3.Cross(direction,NVector3.UnitY);if(side.LengthSquared()<.0001f)side=NVector3.UnitX;else side=NVector3.Normalize(side);float size=Math.Clamp(delta.Length()*.12f,.12f,.5f);AddCamLine(lines,b,b-direction*size+side*size*.45f);AddCamLine(lines,b,b-direction*size-side*size*.45f);
    }
    private void AddCamEditHandles(List<float>[] axes,List<float> selectedLines,List<float> selectedFace,CamEntry e)
    {
        if(e.CameraType is CamType.Track or CamType.Motion)AddCamTrajectory(selectedLines,e);
        if(CamTransformMode==CamGizmoMode.Frame&&selectedCamFrame>=0&&selectedCamFrame<e.Frames.Count){CamFrame frame=e.Frames[selectedCamFrame];NVector3 p=CamVectorToWorld(selectedCamTarget?frame.Target:frame.Position);float s=CamScreenSize(p,16f);AddCamLine(selectedLines,p-new NVector3(s,0,0),p+new NVector3(s,0,0));AddCamLine(selectedLines,p-new NVector3(0,s,0),p+new NVector3(0,s,0));AddCamLine(selectedLines,p-new NVector3(0,0,s),p+new NVector3(0,0,s));AddCamArrow(axes[1],p,NVector3.UnitY,CamGizmoLength(e));return;}
        if(CamTransformMode==CamGizmoMode.Vertex){CamWorldYRange(e,out _,out float y);for(int i=0;i<e.Vertices.Count;i++){NVector3 p=CamToWorld(e.Vertices[i].Position,y);float s=CamScreenSize(p,i==selectedCamVertex?15f:10f);List<float> output=i==selectedCamVertex?selectedLines:axes[1];AddCamLine(output,p-new NVector3(s,0,0),p+new NVector3(s,0,0));AddCamLine(output,p-new NVector3(0,s,0),p+new NVector3(0,s,0));AddCamLine(output,p-new NVector3(0,0,s),p+new NVector3(0,0,s));}}
        else if(CamTransformMode==CamGizmoMode.Face&&selectedCamFace>=0){CamWorldYRange(e,out float y0,out float y1);var b=e.Vertices.Select(v=>CamToWorld(v.Position,y0)).ToArray();var t=e.Vertices.Select(v=>CamToWorld(v.Position,y1)).ToArray();if(selectedCamFace<e.Vertices.Count){int i=selectedCamFace,j=(i+1)%e.Vertices.Count;AddCamQuad(selectedFace,b[i],b[j],t[j],t[i]);AddCamLine(selectedLines,b[i],b[j]);AddCamLine(selectedLines,b[j],t[j]);AddCamLine(selectedLines,t[j],t[i]);AddCamLine(selectedLines,t[i],b[i]);}else{NVector3[] ring=selectedCamFace==e.Vertices.Count?b:t;for(int i=1;i<ring.Length-1;i++)AddCamTriangle(selectedFace,ring[0],ring[i],ring[i+1]);for(int i=0;i<ring.Length;i++)AddCamLine(selectedLines,ring[i],ring[(i+1)%ring.Length]);}}
    }
    private static void EnsureCam(ref int vao,ref int vbo){if(vao==0){vao=GL.GenVertexArray();vbo=GL.GenBuffer();}}
    private static void AddCamEntry(CamEntry e,List<float> lines,List<float> faces){if(e.Vertices.Count>=3){CamWorldYRange(e,out float y0,out float y1);var b=e.Vertices.Select(v=>CamToWorld(v.Position,y0)).ToArray();var t=e.Vertices.Select(v=>CamToWorld(v.Position,y1)).ToArray();for(int i=0;i<b.Length;i++){int j=(i+1)%b.Length;AddCamLine(lines,b[i],b[j]);AddCamLine(lines,t[i],t[j]);AddCamLine(lines,b[i],t[i]);AddCamQuad(faces,b[i],b[j],t[j],t[i]);}for(int i=1;i<b.Length-1;i++){AddCamTriangle(faces,b[0],b[i+1],b[i]);AddCamTriangle(faces,t[0],t[i],t[i+1]);}}foreach(CamFrame f in e.Frames){NVector3 p=CamVectorToWorld(f.Position),t=CamVectorToWorld(f.Target),forward=t-p;if(forward.LengthSquared()<.0001f)forward=NVector3.UnitZ;forward=NVector3.Normalize(forward);NVector3 right=NVector3.Cross(NVector3.UnitY,forward);if(right.LengthSquared()<.0001f)right=NVector3.UnitX;else right=NVector3.Normalize(right);NVector3 up=NVector3.Normalize(NVector3.Cross(forward,right));float s=.42f;NVector3 rear=p-forward*s*.55f;AddCamLine(lines,p,t);AddCamLine(lines,rear-right*s,rear+right*s);AddCamLine(lines,rear-up*s*.7f,rear+up*s*.7f);AddCamLine(lines,rear-right*s,p+forward*s);AddCamLine(lines,rear+right*s,p+forward*s);AddCamLine(lines,rear-up*s*.7f,p+forward*s);AddCamLine(lines,rear+up*s*.7f,p+forward*s);float q=.25f;AddCamLine(lines,t-right*q,t+right*q);AddCamLine(lines,t-up*q,t+up*q);}}
    private void DrawCamGpu(){if(!CamVisible||camScene==null)return;GL.Disable(EnableCap.CullFace);GL.Enable(EnableCap.DepthTest);GL.DepthFunc(DepthFunction.Lequal);GL.DepthMask(false);GL.Uniform1(uUnlit,1);GL.Uniform1(uUseTexture,0);GL.Enable(EnableCap.Blend);GL.BlendFunc(BlendingFactor.SrcAlpha,BlendingFactor.OneMinusSrcAlpha);if(camFaceVertexCount>0){GL.Uniform1(uOpacity,.13f);GL.Uniform3(uColor,.62f,.12f,.92f);GL.BindVertexArray(camFaceVao);GL.DrawArrays(PrimitiveType.Triangles,0,camFaceVertexCount);}if(camSelectedFaceVertexCount>0){GL.Uniform1(uOpacity,.28f);GL.Uniform3(uColor,1f,.65f,.08f);GL.BindVertexArray(camSelectedFaceVao);GL.DrawArrays(PrimitiveType.Triangles,0,camSelectedFaceVertexCount);}if(camEditFaceVertexCount>0){GL.Uniform1(uOpacity,.58f);GL.Uniform3(uColor,.05f,.85f,1f);GL.BindVertexArray(camEditFaceVao);GL.DrawArrays(PrimitiveType.Triangles,0,camEditFaceVertexCount);}GL.Uniform1(uOpacity,1f);GL.Disable(EnableCap.Blend);if(camVertexCount>0){GL.Uniform3(uColor,.75f,.2f,1f);GL.BindVertexArray(camVao);GL.LineWidth(2f);GL.DrawArrays(PrimitiveType.Lines,0,camVertexCount);}if(camSelectedVertexCount>0){GL.Uniform3(uColor,1f,.75f,.12f);GL.BindVertexArray(camSelectedVao);GL.LineWidth(4f);GL.DrawArrays(PrimitiveType.Lines,0,camSelectedVertexCount);}if(camEditVertexCount>0){GL.Uniform3(uColor,.05f,.9f,1f);GL.BindVertexArray(camEditVao);GL.LineWidth(7f);GL.DrawArrays(PrimitiveType.Lines,0,camEditVertexCount);}var colors=new[]{(1f,.15f,.12f),(.2f,.95f,.25f),(.12f,.48f,1f)};for(int i=0;i<3;i++)if(camGizmoCounts[i]>0){GL.Uniform3(uColor,colors[i].Item1,colors[i].Item2,colors[i].Item3);GL.BindVertexArray(camGizmoVaos[i]);GL.LineWidth(5f);GL.DrawArrays(PrimitiveType.Lines,0,camGizmoCounts[i]);}GL.LineWidth(1f);GL.DepthMask(true);GL.Enable(EnableCap.DepthTest);GL.Enable(EnableCap.CullFace);}
    private void DrawCamFrameLabelsGpu()
    {
        CamEntry? entry=SelectedCam();if(entry==null||entry.CameraType is not(CamType.Track or CamType.Motion)||entry.Frames.Count==0||labelShaderProgram==0)return;
        GL.Disable(EnableCap.DepthTest);GL.Disable(EnableCap.CullFace);GL.Enable(EnableCap.Blend);GL.BlendFunc(BlendingFactor.SrcAlpha,BlendingFactor.OneMinusSrcAlpha);GL.UseProgram(labelShaderProgram);GL.ActiveTexture(TextureUnit.Texture0);GL.Uniform1(labelTextureUniform,0);GL.BindVertexArray(labelVao);
        for(int i=0;i<entry.Frames.Count;i++)
        {
            if(!TryProjectWorldToScreen(CamVectorToWorld(entry.Frames[i].Position),out PointF screen))continue;LabelTexture label=GetOrCreateLabelTexture($"F{i:00}",selectedCamFrames.Contains(i));float left=screen.X-label.Width*.5f,top=screen.Y-label.Height-13f;if(left+label.Width<0||top+label.Height<0||left>ClientSize.Width||top>ClientSize.Height)continue;float x0=left/ClientSize.Width*2f-1f,x1=(left+label.Width)/ClientSize.Width*2f-1f,y0=1f-top/ClientSize.Height*2f,y1=1f-(top+label.Height)/ClientSize.Height*2f;float[] quad={x0,y0,0f,0f,x0,y1,0f,1f,x1,y1,1f,1f,x0,y0,0f,0f,x1,y1,1f,1f,x1,y0,1f,0f};GL.BindTexture(TextureTarget.Texture2D,label.TextureId);GL.BindBuffer(BufferTarget.ArrayBuffer,labelVbo);GL.BufferData(BufferTarget.ArrayBuffer,quad.Length*sizeof(float),quad,BufferUsageHint.StreamDraw);GL.DrawArrays(PrimitiveType.Triangles,0,6);
        }
        GL.BindTexture(TextureTarget.Texture2D,0);GL.BindBuffer(BufferTarget.ArrayBuffer,0);GL.BindVertexArray(0);GL.UseProgram(0);GL.Disable(EnableCap.Blend);GL.Enable(EnableCap.DepthTest);GL.Enable(EnableCap.CullFace);
    }
    public bool HandleCamClick(Point mouse)
    {
        CamEntry[] hits=PickCams(mouse);if(hits.Length==0){ResetCamPickCycle();return false;}int[] ids=hits.Select(x=>x.FileOrder).ToArray();bool samePoint=Math.Abs(mouse.X-camCyclePoint.X)<=5&&Math.Abs(mouse.Y-camCyclePoint.Y)<=5;bool sameStack=samePoint&&ids.SequenceEqual(camCycleEntries);camCycleIndex=sameStack?(camCycleIndex+1)%hits.Length:0;camCyclePoint=mouse;camCycleEntries=ids;CamEntry hit=hits[camCycleIndex];selectedCamEntry=hit.FileOrder;camGpuDirty=true;CamEntrySelected?.Invoke(hit);Invalidate();return true;
    }
    private CamEntry[] PickCams(Point mouse)
    {
        if(!CamVisible||camScene==null||!TryBuildPickRay(mouse,out NVector3 o,out NVector3 d))return Array.Empty<CamEntry>();var hits=new List<(CamEntry Entry,float Size,float Distance)>();foreach(CamEntry e in camScene.Entries){var tris=new List<(NVector3,NVector3,NVector3)>();BuildCamPickFaces(e,tris);float nearest=float.PositiveInfinity;foreach(var t in tris)if(RayTriangle(o,d,t.Item1,t.Item2,t.Item3,out float dist)&&dist>=0&&dist<nearest)nearest=dist;if(float.IsFinite(nearest))hits.Add((e,CamVolumeSize(e),nearest));}return hits.OrderByDescending(x=>x.Size).ThenBy(x=>x.Distance).ThenBy(x=>x.Entry.FileOrder).Select(x=>x.Entry).ToArray();
    }
    private static float CamVolumeSize(CamEntry e){if(e.Vertices.Count<3)return 0f;double area=0;for(int i=0;i<e.Vertices.Count;i++){NVector3 a=e.Vertices[i].Position,b=e.Vertices[(i+1)%e.Vertices.Count].Position;area+=(double)a.X*b.Z-(double)b.X*a.Z;}return (float)(Math.Abs(area)*.5*Math.Max(1f,Math.Abs(e.UpperY-e.LowerY)));}
    private void ResetCamPickCycle(){camCycleEntries=Array.Empty<int>();camCycleIndex=-1;camCyclePoint=Point.Empty;}
    private static void BuildCamPickFaces(CamEntry e,List<(NVector3,NVector3,NVector3)> output){if(e.Vertices.Count<3)return;CamWorldYRange(e,out float y0,out float y1);var b=e.Vertices.Select(v=>CamToWorld(v.Position,y0)).ToArray();var t=e.Vertices.Select(v=>CamToWorld(v.Position,y1)).ToArray();for(int i=0;i<b.Length;i++){int j=(i+1)%b.Length;output.Add((b[i],b[j],t[j]));output.Add((b[i],t[j],t[i]));}for(int i=1;i<b.Length-1;i++){output.Add((b[0],b[i+1],b[i]));output.Add((t[0],t[i],t[i+1]));}}
    public bool TryBeginCamDrag(Point mouse)
    {
        CamEntry? e=SelectedCam();if(!CamVisible||e==null)return false;int axis;
        if(CamTransformMode==CamGizmoMode.Frame){if(selectedCamFrame>=0&&selectedCamFrame<e.Frames.Count){axis=PickCamFrameAxis(mouse,e);if(axis>0){CamFrame f=e.Frames[selectedCamFrame];if(selectedCamFrames.Count>1){selectedCamTarget=false;camDragFrameGroup=selectedCamFrames.Where(i=>i>=0&&i<e.Frames.Count).Select(i=>e.Frames[i]).ToDictionary(x=>x,x=>(x.Position,x.Target));camDragFramePoint=f.Position;}else{camDragFrameGroup=null;camDragFramePoint=selectedCamTarget?f.Target:f.Position;}camDragVertices=new();camDragAxis=axis;camDragMouse=mouse;camGpuDirty=true;return true;}}if(!PickCamFramePoint(mouse,e,out selectedCamFrame,out selectedCamTarget))return false;selectedCamFrames.Clear();selectedCamFrames.Add(selectedCamFrame);camPointClickConsumed=true;CamFrameSelected?.Invoke(selectedCamFrame,selectedCamTarget);camGpuDirty=true;Invalidate();return true;}
        if(CamTransformMode==CamGizmoMode.Vertex){axis=selectedCamVertex>=0?PickCamAxis(mouse,e):0;if(axis==0){int vertex=PickCamVertex(mouse,e);if(vertex<0)return false;selectedCamVertex=vertex;selectedCamFace=-1;CamVertexSelected?.Invoke(vertex);axis=7;}}
        else if(CamTransformMode==CamGizmoMode.Face){int face=PickCamFace(mouse,e);if(face<0)return false;selectedCamFace=face;selectedCamVertex=-1;CamVertexSelected?.Invoke(null);axis=face>=e.Vertices.Count?8:7;}
        else{axis=PickCamAxis(mouse,e);if(axis==0)return false;}
        float planeY=CamRawYToWorld((e.LowerY+e.UpperY)*.5f);if(axis==7&&!TryScreenPointOnHorizontalPlane(mouse,planeY,out camDragPlaneStart))return false;camDragAxis=axis;camDragMouse=mouse;camDragVertices=e.Vertices.Select(x=>x.Position).ToList();camDragLower=e.LowerY;camDragUpper=e.UpperY;camGpuDirty=true;Invalidate();return true;
    }
    public void UpdateCamDrag(Point mouse)
    {
        CamEntry? e=SelectedCam();if(e==null||camDragVertices==null)return;if(camDragAxis==8){NVector3 origin=CamGizmoOrigin(e);float pixelsPerWorld=1f;if(TryProjectWorldToScreen(origin,out PointF a0)&&TryProjectWorldToScreen(origin+NVector3.UnitY,out PointF b0))pixelsPerWorld=Math.Max(.05f,MathF.Abs(b0.Y-a0.Y));float heightRawDelta=-(mouse.Y-camDragMouse.Y)/pixelsPerWorld/CamWorldScale;if(selectedCamFace==e.Vertices.Count)e.LowerY=Math.Min(camDragUpper-.01f,camDragLower+heightRawDelta);else e.UpperY=Math.Max(camDragLower+.01f,camDragUpper+heightRawDelta);camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();return;}if(camDragAxis==7){float y=CamRawYToWorld((camDragLower+camDragUpper)*.5f);if(!TryScreenPointOnHorizontalPlane(mouse,y,out NVector3 now))return;NVector3 delta=(now-camDragPlaneStart)/CamWorldScale;if(CamTransformMode==CamGizmoMode.Vertex&&selectedCamVertex>=0&&selectedCamVertex<e.Vertices.Count)e.Vertices[selectedCamVertex].Position=camDragVertices[selectedCamVertex]+new NVector3(delta.X,0,delta.Z);else if(CamTransformMode==CamGizmoMode.Face&&selectedCamFace>=0&&selectedCamFace<e.Vertices.Count){int j=(selectedCamFace+1)%e.Vertices.Count;e.Vertices[selectedCamFace].Position=camDragVertices[selectedCamFace]+new NVector3(delta.X,0,delta.Z);e.Vertices[j].Position=camDragVertices[j]+new NVector3(delta.X,0,delta.Z);}camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();return;}NVector3 axis=camDragAxis is 1?NVector3.UnitX:camDragAxis is 3?NVector3.UnitZ:camDragAxis is 4?-NVector3.UnitY:NVector3.UnitY;NVector3 c=CamGizmoOrigin(e);float len=CamGizmoLength(e);
        if(!TryProjectWorldToScreen(c,out PointF a)||!TryProjectWorldToScreen(c+axis*len,out PointF b))return;var sa=new System.Numerics.Vector2(b.X-a.X,b.Y-a.Y);float pixels=sa.Length();if(pixels<=.1f)return;sa/=pixels;var md=new System.Numerics.Vector2(mouse.X-camDragMouse.X,mouse.Y-camDragMouse.Y);float rawDelta=System.Numerics.Vector2.Dot(md,sa)*len/pixels/CamWorldScale;
        if(CamTransformMode==CamGizmoMode.Frame&&selectedCamFrame>=0&&selectedCamFrame<e.Frames.Count){NVector3 delta=axis*rawDelta;if(camDragFrameGroup!=null){foreach(var pair in camDragFrameGroup){pair.Key.Position=pair.Value.Position+delta;pair.Key.Target=pair.Value.Target+delta;}}else{CamFrame frame=e.Frames[selectedCamFrame];NVector3 value=camDragFramePoint+delta;if(selectedCamTarget)frame.Target=value;else frame.Position=value;}camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();return;}
        if(CamTransformMode==CamGizmoMode.Move){for(int i=0;i<e.Vertices.Count;i++)e.Vertices[i].Position=camDragVertices[i]+axis*rawDelta;if(camDragAxis==2){e.LowerY=camDragLower+rawDelta;e.UpperY=camDragUpper+rawDelta;}}
        else if(CamTransformMode==CamGizmoMode.Vertex&&selectedCamVertex>=0&&selectedCamVertex<e.Vertices.Count){e.Vertices[selectedCamVertex].Position=camDragVertices[selectedCamVertex]+axis*rawDelta;}
        else if(CamTransformMode==CamGizmoMode.Scale){NVector3 rawCenter=new(camDragVertices.Average(v=>v.X),(camDragLower+camDragUpper)*.5f,camDragVertices.Average(v=>v.Z));if(camDragAxis is 4 or 5){if(camDragAxis==4)e.LowerY=Math.Min(camDragUpper-.01f,camDragLower-rawDelta);else e.UpperY=Math.Max(camDragLower+.01f,camDragUpper+rawDelta);}else{float extent=camDragAxis==1?camDragVertices.Max(v=>Math.Abs(v.X-rawCenter.X)):camDragVertices.Max(v=>Math.Abs(v.Z-rawCenter.Z));float factor=Math.Max(.01f,1f+rawDelta/Math.Max(1f,extent));for(int i=0;i<e.Vertices.Count;i++){NVector3 p=camDragVertices[i];e.Vertices[i].Position=camDragAxis==1?new NVector3(rawCenter.X+(p.X-rawCenter.X)*factor,p.Y,p.Z):new NVector3(p.X,p.Y,rawCenter.Z+(p.Z-rawCenter.Z)*factor);}}}
        camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();
    }
    public void EndCamDrag(){CamEntry? e=SelectedCam();if(e!=null&&CamTransformMode==CamGizmoMode.Frame&&selectedCamFrame>=0&&selectedCamFrame<e.Frames.Count){if(camDragFrameGroup!=null){var before=camDragFrameGroup.ToDictionary(x=>x.Key,x=>x.Value);var after=camDragFrameGroup.Keys.ToDictionary(x=>x,x=>(x.Position,x.Target));if(before.Any(x=>after[x.Key]!=x.Value)){RegisterCamEdit(()=>ApplyCamFrameGroup(e,before),()=>ApplyCamFrameGroup(e,after));}}else{CamFrame f=e.Frames[selectedCamFrame];NVector3 after=selectedCamTarget?f.Target:f.Position,before=camDragFramePoint;if(before!=after)RegisterCamEdit(()=>ApplyCamFramePoint(e,f,selectedCamTarget,before),()=>ApplyCamFramePoint(e,f,selectedCamTarget,after));}if(camScene!=null)camScene.IsModified=true;CamEntryEdited?.Invoke(e);}else if(e!=null&&camDragVertices!=null){CamShapeState before=new(camDragVertices.ToArray(),camDragLower,camDragUpper),after=CamShapeState.From(e);if(!before.Equals(after))RegisterCamEdit(()=>ApplyCamShape(e,before),()=>ApplyCamShape(e,after));if(camScene!=null)camScene.IsModified=true;CamEntryEdited?.Invoke(e);}camDragAxis=0;camDragVertices=null;camDragFrameGroup=null;camGpuDirty=true;}
    private void ApplyCamFrameGroup(CamEntry e,IReadOnlyDictionary<CamFrame,(NVector3 Position,NVector3 Target)> state){foreach(var pair in state){pair.Key.Position=pair.Value.Position;pair.Key.Target=pair.Value.Target;}if(camScene!=null)camScene.IsModified=true;camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();}
    private void ApplyCamFramePoint(CamEntry e,CamFrame f,bool targetPoint,NVector3 value){if(targetPoint)f.Target=value;else f.Position=value;if(camScene!=null)camScene.IsModified=true;camGpuDirty=true;CamEntryEdited?.Invoke(e);Invalidate();}
    private bool PickCamFramePoint(Point mouse,CamEntry e,out int frameIndex,out bool targetPoint){frameIndex=-1;targetPoint=false;float best=18f*18f;for(int i=0;i<e.Frames.Count;i++){NVector3[] points={CamVectorToWorld(e.Frames[i].Position),CamVectorToWorld(e.Frames[i].Target)};for(int k=0;k<2;k++)if(TryProjectWorldToScreen(points[k],out PointF p)){float dx=p.X-mouse.X,dy=p.Y-mouse.Y,d=dx*dx+dy*dy;if(d<best){best=d;frameIndex=i;targetPoint=k==1;}}}return frameIndex>=0;}
    private int PickCamFrameAxis(Point mouse,CamEntry e){NVector3 c=CamGizmoOrigin(e);float len=CamGizmoLength(e);if(!TryProjectWorldToScreen(c,out PointF a))return 0;int axis=0;float best=11f;NVector3[] ends={c+NVector3.UnitX*len,c+NVector3.UnitY*len,c+NVector3.UnitZ*len};for(int i=0;i<3;i++)if(TryProjectWorldToScreen(ends[i],out PointF b)){float d=DistancePointToSegment(mouse,a,b);if(d<best){best=d;axis=i+1;}}return axis;}
    private int PickCamVertex(Point mouse,CamEntry e){CamWorldYRange(e,out _,out float y);int best=-1;float bestSq=15f*15f;for(int i=0;i<e.Vertices.Count;i++)if(TryProjectWorldToScreen(CamToWorld(e.Vertices[i].Position,y),out PointF p)){float dx=p.X-mouse.X,dy=p.Y-mouse.Y,d=dx*dx+dy*dy;if(d<bestSq){bestSq=d;best=i;}}return best;}
    private int PickCamFace(Point mouse,CamEntry e){if(!TryBuildPickRay(mouse,out NVector3 o,out NVector3 d)||e.Vertices.Count<3)return-1;CamWorldYRange(e,out float y0,out float y1);float best=float.PositiveInfinity;int face=-1;var bottom=e.Vertices.Select(v=>CamToWorld(v.Position,y0)).ToArray();var top=e.Vertices.Select(v=>CamToWorld(v.Position,y1)).ToArray();void Hit(NVector3 a,NVector3 b,NVector3 c,int id){if(RayTriangle(o,d,a,b,c,out float distance)&&distance<best){best=distance;face=id;}}for(int i=0;i<e.Vertices.Count;i++){int j=(i+1)%e.Vertices.Count;Hit(bottom[i],bottom[j],top[j],i);Hit(bottom[i],top[j],top[i],i);}for(int i=1;i<e.Vertices.Count-1;i++){Hit(bottom[0],bottom[i+1],bottom[i],e.Vertices.Count);Hit(top[0],top[i],top[i+1],e.Vertices.Count+1);}return face;}
    private int PickCamAxis(Point mouse,CamEntry e){if(CamTransformMode==CamGizmoMode.Vertex&&(selectedCamVertex<0||selectedCamVertex>=e.Vertices.Count))return 0;NVector3 c=CamGizmoOrigin(e);float len=CamGizmoLength(e);if(!TryProjectWorldToScreen(c,out PointF a))return 0;if(CamTransformMode==CamGizmoMode.Vertex&&MathF.Sqrt((mouse.X-a.X)*(mouse.X-a.X)+(mouse.Y-a.Y)*(mouse.Y-a.Y))<=13f)return 0;int axis=0;float best=11f;NVector3[] ends={c+NVector3.UnitX*len,c+NVector3.UnitY*len,c+NVector3.UnitZ*len};for(int i=0;i<3;i++){if(CamTransformMode!=CamGizmoMode.Move&&i==1)continue;if(TryProjectWorldToScreen(ends[i],out PointF b)){float dist=DistancePointToSegment(mouse,a,b);if(dist<best){best=dist;axis=i+1;}}}if(CamTransformMode==CamGizmoMode.Scale){CamWorldYRange(e,out float bottom,out float top);NVector3[] height={new(c.X,bottom,c.Z),new(c.X,top,c.Z)};for(int i=0;i<2;i++)if(TryProjectWorldToScreen(height[i],out PointF p)){float d=MathF.Sqrt((mouse.X-p.X)*(mouse.X-p.X)+(mouse.Y-p.Y)*(mouse.Y-p.Y));if(d<best){best=d;axis=i+4;}}}return axis;}
    private CamEntry? SelectedCam()=>camScene?.Entries.FirstOrDefault(x=>x.FileOrder==selectedCamEntry);
    private NVector3 CamGizmoOrigin(CamEntry e){if(CamTransformMode==CamGizmoMode.Frame&&selectedCamFrame>=0&&selectedCamFrame<e.Frames.Count){CamFrame f=e.Frames[selectedCamFrame];return CamVectorToWorld(selectedCamTarget?f.Target:f.Position);}CamWorldYRange(e,out float bottom,out float top);float y=(bottom+top)*.5f;if(CamTransformMode==CamGizmoMode.Vertex&&selectedCamVertex>=0&&selectedCamVertex<e.Vertices.Count)return CamToWorld(e.Vertices[selectedCamVertex].Position,top);if(CamTransformMode==CamGizmoMode.Face&&selectedCamFace>=0){if(selectedCamFace<e.Vertices.Count){int j=(selectedCamFace+1)%e.Vertices.Count;return(CamToWorld(e.Vertices[selectedCamFace].Position,y)+CamToWorld(e.Vertices[j].Position,y))*.5f;}NVector3 center=CamCenter(e);return new NVector3(center.X,selectedCamFace==e.Vertices.Count?bottom:top,center.Z);}return CamCenter(e);}
    public void FocusCam(CamEntry? e){if(e==null)return;target=CamCenter(e);float width=e.Vertices.Count==0?10f:e.Vertices.Max(v=>NVector3.Distance(new NVector3(v.X,0,v.Z)*CamWorldScale,new NVector3(target.X,0,target.Z)));float height=Math.Abs(e.UpperY-e.LowerY)*CamWorldScale;distance=Math.Clamp(Math.Max(width,height)*2.4f,8f,2000f);cameraPosition=target-GetForward()*distance;Invalidate();}
    public (NVector3 Position,NVector3 Target,float Fov) GetCamCreationPose()
    {
        const float ahead=10f;
        return(CamWorldToRaw(cameraPosition),CamWorldToRaw(cameraPosition+GetForward()*ahead),60f);
    }
    public void RegisterCamEdit(Action undo,Action redo){camUndo.Push((undo,redo));camRedo.Clear();while(camUndo.Count>100){var keep=camUndo.Reverse().Take(100).Reverse().ToArray();camUndo.Clear();foreach(var item in keep)camUndo.Push(item);}}
    public bool UndoCamEdit(){if(camUndo.Count==0)return false;var edit=camUndo.Pop();edit.Undo();camRedo.Push(edit);return true;}
    public bool RedoCamEdit(){if(camRedo.Count==0)return false;var edit=camRedo.Pop();edit.Redo();camUndo.Push(edit);return true;}
    private readonly record struct CamShapeState(NVector3[] Vertices,float Lower,float Upper){public static CamShapeState From(CamEntry e)=>new(e.Vertices.Select(v=>v.Position).ToArray(),e.LowerY,e.UpperY);public bool Equals(CamShapeState other)=>Lower==other.Lower&&Upper==other.Upper&&Vertices.SequenceEqual(other.Vertices);public override int GetHashCode()=>HashCode.Combine(Lower,Upper,Vertices.Length);}
    private void ApplyCamShape(CamEntry e,CamShapeState state){for(int i=0;i<Math.Min(e.Vertices.Count,state.Vertices.Length);i++)e.Vertices[i].Position=state.Vertices[i];e.LowerY=state.Lower;e.UpperY=state.Upper;if(camScene!=null)camScene.IsModified=true;selectedCamEntry=e.FileOrder;camGpuDirty=true;CamEntryEdited?.Invoke(e);CamEntrySelected?.Invoke(e);Invalidate();}
    private static NVector3 CamCenter(CamEntry e){if(e.Vertices.Count==0)return NVector3.Zero;return new NVector3(e.Vertices.Average(v=>v.X)*CamWorldScale,CamRawYToWorld((e.LowerY+e.UpperY)*.5f),e.Vertices.Average(v=>v.Z)*CamWorldScale);}
    private float CamGizmoLength(CamEntry e)=>CamScreenSize(CamGizmoOrigin(e),72f);
    private float CamScreenSize(NVector3 origin,float pixels){float depth=Math.Max(.05f,NVector3.Dot(origin-cameraPosition,GetForward()));float worldPerPixel=2f*depth*MathF.Tan(MathF.PI/6f)/Math.Max(1,ClientSize.Height);return Math.Clamp(worldPerPixel*pixels,.03f,10000f);}
    private static NVector3 CamToWorld(NVector3 p,float y)=>new(p.X*CamWorldScale,y,p.Z*CamWorldScale);
    private static NVector3 CamVectorToWorld(NVector3 p)=>new(p.X*CamWorldScale,CamRawYToWorld(p.Y),p.Z*CamWorldScale);
    private static NVector3 CamWorldToRaw(NVector3 p)=>p/CamWorldScale;
    private static float CamRawYToWorld(float rawY)=>rawY*CamWorldScale;
    private static void CamWorldYRange(CamEntry e,out float bottom,out float top){float a=CamRawYToWorld(e.LowerY),b=CamRawYToWorld(e.UpperY);bottom=Math.Min(a,b);top=Math.Max(a,b);}
    private static void AddCamArrow(List<float> v,NVector3 p,NVector3 axis,float len){NVector3 end=p+axis*len;AddCamLine(v,p,end);NVector3 side=Math.Abs(axis.Y)>.5f?NVector3.UnitX:NVector3.UnitY;AddCamLine(v,end,end-axis*.12f*len+side*.05f*len);AddCamLine(v,end,end-axis*.12f*len-side*.05f*len);}
    private static void AddCamLine(List<float> v,NVector3 a,NVector3 b){AddCamPoint(v,a);AddCamPoint(v,b);}private static void AddCamQuad(List<float> v,NVector3 a,NVector3 b,NVector3 c,NVector3 d){AddCamTriangle(v,a,b,c);AddCamTriangle(v,a,c,d);}private static void AddCamTriangle(List<float> v,NVector3 a,NVector3 b,NVector3 c){AddCamPoint(v,a);AddCamPoint(v,b);AddCamPoint(v,c);}private static void AddCamPoint(List<float> v,NVector3 p){v.Add(p.X);v.Add(p.Y);v.Add(p.Z);v.Add(0);v.Add(1);v.Add(0);}
    private void DisposeCamGpu(){DeleteCam(ref camVao,ref camVbo);DeleteCam(ref camSelectedVao,ref camSelectedVbo);DeleteCam(ref camFaceVao,ref camFaceVbo);DeleteCam(ref camSelectedFaceVao,ref camSelectedFaceVbo);DeleteCam(ref camEditVao,ref camEditVbo);DeleteCam(ref camEditFaceVao,ref camEditFaceVbo);for(int i=0;i<3;i++)DeleteCam(ref camGizmoVaos[i],ref camGizmoVbos[i]);}private static void DeleteCam(ref int vao,ref int vbo){if(vbo!=0)GL.DeleteBuffer(vbo);if(vao!=0)GL.DeleteVertexArray(vao);vao=vbo=0;}
}
