using RE4_PS2_MOD_WORKSPACE.Core.Visual;
using OpenTK.Graphics.OpenGL4;
using NVector3=System.Numerics.Vector3;
namespace RE4_PS2_MOD_WORKSPACE;
public enum FseGizmoMode{Move,Vertex,Face}
public sealed partial class ScenarioViewport
{
 const float SoundWorldScale=.01f;EseScene? eseScene;FseScene? fseScene;int selectedEse=-1,selectedFse=-1,selectedFseVertex=-1,selectedFseFace=-1;bool soundGpuDirty=true;
 int eseVao,eseVbo,eseCount,fseVao,fseVbo,fseCount,fseFaceVao,fseFaceVbo,fseFaceCount,soundSelectedVao,soundSelectedVbo,soundSelectedCount,soundSelectedFaceVao,soundSelectedFaceVbo,soundSelectedFaceCount;readonly int[] fseGizmoVaos=new int[3],fseGizmoVbos=new int[3],fseGizmoCounts=new int[3];
 FseEntry? draggingFse;Point fseDragMouse;FseState fseDragStart;NVector3 fseDragOrigin,fsePlaneStart;int fseDragAxis;readonly Stack<(Action Undo,Action Redo)> fseUndo=new(),fseRedo=new();
 public event Action<EseEntry?>? EseEntryClicked;public event Action<FseEntry?>? FseEntryClicked;public event Action<FseEntry>? FseEntryEdited;public bool SoundVisible{get;set;}=true;public bool FseEditingEnabled{get;set;}public FseGizmoMode FseTransformMode{get;private set;}=FseGizmoMode.Move;public bool IsSoundDragging=>draggingFse!=null;
 public void SetSoundScenes(EseScene? a,FseScene? b){eseScene=a;fseScene=b;selectedEse=selectedFse=selectedFseVertex=selectedFseFace=-1;fseUndo.Clear();fseRedo.Clear();soundGpuDirty=true;Invalidate();}public void SelectEseEntry(EseEntry? e){selectedEse=e?.FileOrder??-1;selectedFse=-1;soundGpuDirty=true;Invalidate();}public void SelectFseEntry(FseEntry? e){if(selectedFse!=(e?.FileOrder??-1))selectedFseVertex=selectedFseFace=-1;selectedFse=e?.FileOrder??-1;selectedEse=-1;soundGpuDirty=true;Invalidate();}public void SetFseTransformMode(FseGizmoMode m){FseTransformMode=m;selectedFseVertex=selectedFseFace=-1;soundGpuDirty=true;Invalidate();}public void RefreshSoundGeometry(){soundGpuDirty=true;Invalidate();}
 public void FocusEse(EseEntry? e){if(e!=null)FocusSound(e.Position*SoundWorldScale);}public void FocusFse(FseEntry? e){if(e!=null)FocusSound(Center(e));}void FocusSound(NVector3 p){target=p;distance=Math.Max(8,distance);cameraPosition=target-GetForward()*Math.Min(distance,80);Invalidate();Focus();}
 void EnsureSound(){EnsureCam(ref eseVao,ref eseVbo);EnsureCam(ref fseVao,ref fseVbo);EnsureCam(ref fseFaceVao,ref fseFaceVbo);EnsureCam(ref soundSelectedVao,ref soundSelectedVbo);EnsureCam(ref soundSelectedFaceVao,ref soundSelectedFaceVbo);for(int i=0;i<3;i++)EnsureCam(ref fseGizmoVaos[i],ref fseGizmoVbos[i]);}
 void UploadSound(){soundGpuDirty=false;EnsureSound();var ep=new List<float>();var l=new List<float>();var f=new List<float>();var sl=new List<float>();var sf=new List<float>();if(eseScene!=null)foreach(var e in eseScene.Entries)Marker(e.FileOrder==selectedEse?sl:ep,e);if(fseScene!=null)foreach(var e in fseScene.Entries)Geometry(e,e.FileOrder==selectedFse?sl:l,e.FileOrder==selectedFse?sf:f);var ax=new[]{new List<float>(),new List<float>(),new List<float>()};var s=SelectedFse();if(s!=null&&FseEditingEnabled)EditGeometry(s,sl,sf,ax);UploadLineBuffer(eseVao,eseVbo,ep,out eseCount);UploadLineBuffer(fseVao,fseVbo,l,out fseCount);UploadLineBuffer(fseFaceVao,fseFaceVbo,f,out fseFaceCount);UploadLineBuffer(soundSelectedVao,soundSelectedVbo,sl,out soundSelectedCount);UploadLineBuffer(soundSelectedFaceVao,soundSelectedFaceVbo,sf,out soundSelectedFaceCount);for(int i=0;i<3;i++)UploadLineBuffer(fseGizmoVaos[i],fseGizmoVbos[i],ax[i],out fseGizmoCounts[i]);}
 static void Marker(List<float> v,EseEntry e){var p=e.Position*SoundWorldScale;float r=1.5f;AddCamLine(v,p-new NVector3(r,0,0),p+new NVector3(r,0,0));AddCamLine(v,p-new NVector3(0,r,0),p+new NVector3(0,r,0));AddCamLine(v,p-new NVector3(0,0,r),p+new NVector3(0,0,r));}
 static void Rings(FseEntry e,out NVector3[] b,out NVector3[] t){float y0=Math.Min(e.BaseY,e.Height)*SoundWorldScale,y1=Math.Max(e.BaseY,e.Height)*SoundWorldScale;if(e.Shape==FseZoneShape.Circle){b=new NVector3[32];t=new NVector3[32];for(int i=0;i<32;i++){float a=MathF.Tau*i/32,r=MathF.Abs(e.Radius)*SoundWorldScale;b[i]=new(e.Corner0X*SoundWorldScale+MathF.Cos(a)*r,y0,e.Corner0Z*SoundWorldScale+MathF.Sin(a)*r);t[i]=new(b[i].X,y1,b[i].Z);}}else{b=new[]{new NVector3(e.Corner0X*SoundWorldScale,y0,e.Corner0Z*SoundWorldScale),new(e.Corner1X*SoundWorldScale,y0,e.Corner1Z*SoundWorldScale),new(e.Corner2X*SoundWorldScale,y0,e.Corner2Z*SoundWorldScale),new(e.Corner3X*SoundWorldScale,y0,e.Corner3Z*SoundWorldScale)};t=b.Select(x=>new NVector3(x.X,y1,x.Z)).ToArray();}}
 static void Geometry(FseEntry e,List<float> l,List<float> f){Rings(e,out var b,out var t);for(int i=0;i<b.Length;i++){int j=(i+1)%b.Length;AddCamLine(l,b[i],b[j]);AddCamLine(l,t[i],t[j]);AddCamLine(l,b[i],t[i]);AddCamQuad(f,b[i],b[j],t[j],t[i]);}for(int i=1;i<b.Length-1;i++){AddCamTriangle(f,b[0],b[i+1],b[i]);AddCamTriangle(f,t[0],t[i],t[i+1]);}}
 void EditGeometry(FseEntry e,List<float> l,List<float> f,List<float>[] ax){Rings(e,out var b,out var t);if(FseTransformMode==FseGizmoMode.Vertex){var h=e.Shape==FseZoneShape.Circle?new[]{CenterAt(e,t[0].Y),t[0]}:t;for(int i=0;i<h.Length;i++){float s=CamScreenSize(h[i],i==selectedFseVertex?15:10);AddCamLine(i==selectedFseVertex?l:ax[1],h[i]-new NVector3(s,0,0),h[i]+new NVector3(s,0,0));AddCamLine(i==selectedFseVertex?l:ax[1],h[i]-new NVector3(0,0,s),h[i]+new NVector3(0,0,s));}if(selectedFseVertex<0)return;}if(FseTransformMode==FseGizmoMode.Face&&selectedFseFace>=0){if(selectedFseFace<b.Length){int j=(selectedFseFace+1)%b.Length;AddCamQuad(f,b[selectedFseFace],b[j],t[j],t[selectedFseFace]);}else{var q=selectedFseFace==b.Length?b:t;for(int i=1;i<q.Length-1;i++)AddCamTriangle(f,q[0],q[i],q[i+1]);}}var o=Origin(e);float z=CamScreenSize(o,72);bool horizontal=FseTransformMode==FseGizmoMode.Face&&selectedFseFace>=b.Length;if(horizontal)AddCamArrow(ax[1],o,selectedFseFace==b.Length?-NVector3.UnitY:NVector3.UnitY,z);else{AddCamArrow(ax[0],o,NVector3.UnitX,z);if(FseTransformMode==FseGizmoMode.Move)AddCamArrow(ax[1],o,NVector3.UnitY,z);AddCamArrow(ax[2],o,NVector3.UnitZ,z);}}
 void DrawSoundGpu(){if(!SoundVisible)return;GL.Disable(EnableCap.CullFace);GL.DepthMask(false);GL.Uniform1(uUnlit,1);GL.Uniform1(uUseTexture,0);GL.Enable(EnableCap.Blend);GL.BlendFunc(BlendingFactor.SrcAlpha,BlendingFactor.OneMinusSrcAlpha);GL.Uniform1(uOpacity,.16f);GL.Uniform3(uColor,.12f,.86f,.32f);GL.BindVertexArray(fseFaceVao);GL.DrawArrays(PrimitiveType.Triangles,0,fseFaceCount);GL.Uniform1(uOpacity,.38f);GL.Uniform3(uColor,FseTransformMode==FseGizmoMode.Face&&selectedFseFace>=0?.05f:1f,.72f,FseTransformMode==FseGizmoMode.Face&&selectedFseFace>=0?1f:.08f);GL.BindVertexArray(soundSelectedFaceVao);GL.DrawArrays(PrimitiveType.Triangles,0,soundSelectedFaceCount);GL.Uniform1(uOpacity,1);GL.Disable(EnableCap.Blend);GL.Uniform3(uColor,.25f,.8f,1);GL.BindVertexArray(eseVao);GL.DrawArrays(PrimitiveType.Lines,0,eseCount);GL.Uniform3(uColor,.25f,1,.42f);GL.BindVertexArray(fseVao);GL.DrawArrays(PrimitiveType.Lines,0,fseCount);GL.Uniform3(uColor,1,.78f,.1f);GL.BindVertexArray(soundSelectedVao);GL.LineWidth(4);GL.DrawArrays(PrimitiveType.Lines,0,soundSelectedCount);var c=new[]{(1f,.15f,.12f),(.2f,.95f,.25f),(.12f,.48f,1f)};for(int i=0;i<3;i++){GL.Uniform3(uColor,c[i].Item1,c[i].Item2,c[i].Item3);GL.BindVertexArray(fseGizmoVaos[i]);GL.LineWidth(5);GL.DrawArrays(PrimitiveType.Lines,0,fseGizmoCounts[i]);}GL.LineWidth(1);GL.DepthMask(true);GL.Enable(EnableCap.CullFace);}
 FseEntry? SelectedFse()=>fseScene?.Entries.FirstOrDefault(x=>x.FileOrder==selectedFse);static NVector3 Center(FseEntry e)=>CenterAt(e,(e.BaseY+e.Height)*.5f*SoundWorldScale);static NVector3 CenterAt(FseEntry e,float y)=>new((e.Shape==FseZoneShape.Circle?e.Corner0X:(e.Corner0X+e.Corner1X+e.Corner2X+e.Corner3X)/4)*SoundWorldScale,y,(e.Shape==FseZoneShape.Circle?e.Corner0Z:(e.Corner0Z+e.Corner1Z+e.Corner2Z+e.Corner3Z)/4)*SoundWorldScale);
 NVector3 Origin(FseEntry e){Rings(e,out var b,out var t);if(FseTransformMode==FseGizmoMode.Vertex&&selectedFseVertex>=0)return e.Shape==FseZoneShape.Circle?(selectedFseVertex==0?CenterAt(e,t[0].Y):t[0]):t[selectedFseVertex];if(FseTransformMode==FseGizmoMode.Face&&selectedFseFace>=0){if(selectedFseFace<b.Length){int j=(selectedFseFace+1)%b.Length;return(b[selectedFseFace]+b[j]+t[selectedFseFace]+t[j])*.25f;}return CenterAt(e,selectedFseFace==b.Length?b[0].Y:t[0].Y);}return Center(e);}
 FseEntry? PickFse(Point m){if(!TryBuildPickRay(m,out var o,out var d)||fseScene==null)return null;FseEntry? hit=null;float best=float.MaxValue;foreach(var e in fseScene.Entries){Rings(e,out var b,out var t);void H(NVector3 a,NVector3 q,NVector3 c){if(RayTriangle(o,d,a,q,c,out float x)&&x<best){best=x;hit=e;}}for(int i=0;i<b.Length;i++){int j=(i+1)%b.Length;H(b[i],b[j],t[j]);H(b[i],t[j],t[i]);}for(int i=1;i<b.Length-1;i++){H(b[0],b[i+1],b[i]);H(t[0],t[i],t[i+1]);}}return hit;}
 EseEntry? PickEse(Point p){EseEntry? h=null;float best=18;if(eseScene!=null)foreach(var e in eseScene.Entries)if(TryProjectWorldToScreen(e.Position*SoundWorldScale,out var s)){float d=MathF.Sqrt((s.X-p.X)*(s.X-p.X)+(s.Y-p.Y)*(s.Y-p.Y));if(d<best){best=d;h=e;}}return h;}
 int PickVertex(Point m,FseEntry e){Rings(e,out _,out var t);var h=e.Shape==FseZoneShape.Circle?new[]{CenterAt(e,t[0].Y),t[0]}:t;int z=-1;float best=256;for(int i=0;i<h.Length;i++)if(TryProjectWorldToScreen(h[i],out var p)){float d=(p.X-m.X)*(p.X-m.X)+(p.Y-m.Y)*(p.Y-m.Y);if(d<best){best=d;z=i;}}return z;}
 int PickFace(Point m,FseEntry e){if(!TryBuildPickRay(m,out var o,out var d))return-1;Rings(e,out var b,out var t);int face=-1;float best=float.MaxValue;void H(NVector3 a,NVector3 q,NVector3 c,int id){if(RayTriangle(o,d,a,q,c,out float x)&&x<best){best=x;face=id;}}for(int i=0;i<b.Length;i++){int j=(i+1)%b.Length;H(b[i],b[j],t[j],i);H(b[i],t[j],t[i],i);}for(int i=1;i<b.Length-1;i++){H(b[0],b[i+1],b[i],b.Length);H(t[0],t[i],t[i+1],b.Length+1);}return face;}
 int PickAxis(Point m,FseEntry e){var o=Origin(e);float len=CamScreenSize(o,72);if(!TryProjectWorldToScreen(o,out var a))return 0;int axis=0;float best=11;var ends=new[]{o+NVector3.UnitX*len,o+NVector3.UnitY*len,o+NVector3.UnitZ*len};for(int i=0;i<3;i++){if(FseTransformMode!=FseGizmoMode.Move&&i==1)continue;if(TryProjectWorldToScreen(ends[i],out var b)){float d=DistancePointToSegment(m,a,b);if(d<best){best=d;axis=i+1;}}}return axis;}
 bool TryBeginSoundDrag(Point m){var e=SelectedFse();if(!SoundVisible||!FseEditingEnabled||e==null)return false;int a=PickAxis(m,e);if(a==0&&FseTransformMode==FseGizmoMode.Vertex){selectedFseVertex=PickVertex(m,e);if(selectedFseVertex<0)return false;a=7;}else if(a==0&&FseTransformMode==FseGizmoMode.Face){selectedFseFace=PickFace(m,e);if(selectedFseFace<0)return false;a=selectedFseFace>=(e.Shape==FseZoneShape.Circle?32:4)?8:7;}else if(a==0)return false;draggingFse=e;fseDragStart=FseState.From(e);fseDragMouse=m;fseDragOrigin=Origin(e);fseDragAxis=a;if(a==7&&!TryScreenPointOnHorizontalPlane(m,fseDragOrigin.Y,out fsePlaneStart)){draggingFse=null;return false;}soundGpuDirty=true;Invalidate();return true;}
 void UpdateSoundDrag(Point m){var e=draggingFse;if(e==null)return;fseDragStart.Apply(e);if(fseDragAxis==8){float d=-(m.Y-fseDragMouse.Y)*10;int n=e.Shape==FseZoneShape.Circle?32:4;if(selectedFseFace==n)e.BaseY=fseDragStart.BaseY+d;else e.Height=fseDragStart.Height+d;}else if(fseDragAxis==7&&TryScreenPointOnHorizontalPlane(m,fseDragOrigin.Y,out var now)){var d=(now-fsePlaneStart)/SoundWorldScale;EditXZ(e,d.X,d.Z);}else{var axis=fseDragAxis==1?NVector3.UnitX:fseDragAxis==2?NVector3.UnitY:NVector3.UnitZ;float len=CamScreenSize(fseDragOrigin,72);if(!TryProjectWorldToScreen(fseDragOrigin,out var a)||!TryProjectWorldToScreen(fseDragOrigin+axis*len,out var b))return;var s=new System.Numerics.Vector2(b.X-a.X,b.Y-a.Y);float px=s.Length();if(px<.1)return;s/=px;float d=System.Numerics.Vector2.Dot(new(m.X-fseDragMouse.X,m.Y-fseDragMouse.Y),s)*len/px/SoundWorldScale;if(FseTransformMode==FseGizmoMode.Move){if(fseDragAxis==2){e.BaseY+=d;e.Height+=d;}else Move(e,fseDragAxis==1?d:0,fseDragAxis==3?d:0);}else EditXZ(e,fseDragAxis==1?d:0,fseDragAxis==3?d:0);}Changed(e);}
 void EditXZ(FseEntry e,float x,float z){if(FseTransformMode==FseGizmoMode.Vertex){if(e.Shape==FseZoneShape.Circle){if(selectedFseVertex==0)Move(e,x,z);else e.Radius=Math.Max(.01f,fseDragStart.Radius+x);}else Corner(e,selectedFseVertex,x,z);}else if(FseTransformMode==FseGizmoMode.Face){if(e.Shape==FseZoneShape.Circle)e.Radius=Math.Max(.01f,fseDragStart.Radius+x);else{Corner(e,selectedFseFace,x,z);Corner(e,(selectedFseFace+1)%4,x,z);}}}
 void Changed(FseEntry e){if(fseScene!=null)fseScene.IsModified=true;soundGpuDirty=true;FseEntryEdited?.Invoke(e);Invalidate();}void EndSoundDrag(){var e=draggingFse;if(e!=null){var before=fseDragStart;var after=FseState.From(e);if(!before.Equals(after))RegisterFseEdit(()=>Apply(e,before),()=>Apply(e,after));}draggingFse=null;fseDragAxis=0;}
 bool HandleSoundClick(Point p){if(!SoundVisible)return false;if(FseEditingEnabled&&PickFse(p) is FseEntry f){SelectFseEntry(f);FseEntryClicked?.Invoke(f);return true;}if(PickEse(p) is EseEntry e){SelectEseEntry(e);EseEntryClicked?.Invoke(e);return true;}return false;}
 static void Move(FseEntry e,float x,float z){for(int i=0;i<4;i++)Corner(e,i,x,z);}static void Corner(FseEntry e,int i,float x,float z){if(i==0){e.Corner0X+=x;e.Corner0Z+=z;}else if(i==1){e.Corner1X+=x;e.Corner1Z+=z;}else if(i==2){e.Corner2X+=x;e.Corner2Z+=z;}else if(i==3){e.Corner3X+=x;e.Corner3Z+=z;}}
 void RegisterFseEdit(Action u,Action r){fseUndo.Push((u,r));fseRedo.Clear();}public bool UndoFseEdit(){if(fseUndo.Count==0)return false;var x=fseUndo.Pop();x.Undo();fseRedo.Push(x);return true;}public bool RedoFseEdit(){if(fseRedo.Count==0)return false;var x=fseRedo.Pop();x.Redo();fseUndo.Push(x);return true;}void Apply(FseEntry e,FseState s){s.Apply(e);Changed(e);FseEntryClicked?.Invoke(e);}
 readonly record struct FseState(float BaseY,float Height,float Radius,float X0,float Z0,float X1,float Z1,float X2,float Z2,float X3,float Z3){public static FseState From(FseEntry e)=>new(e.BaseY,e.Height,e.Radius,e.Corner0X,e.Corner0Z,e.Corner1X,e.Corner1Z,e.Corner2X,e.Corner2Z,e.Corner3X,e.Corner3Z);public void Apply(FseEntry e){e.BaseY=BaseY;e.Height=Height;e.Radius=Radius;e.Corner0X=X0;e.Corner0Z=Z0;e.Corner1X=X1;e.Corner1Z=Z1;e.Corner2X=X2;e.Corner2Z=Z2;e.Corner3X=X3;e.Corner3Z=Z3;}}
 void DisposeSoundGpu(){DeleteCam(ref eseVao,ref eseVbo);DeleteCam(ref fseVao,ref fseVbo);DeleteCam(ref fseFaceVao,ref fseFaceVbo);DeleteCam(ref soundSelectedVao,ref soundSelectedVbo);DeleteCam(ref soundSelectedFaceVao,ref soundSelectedFaceVbo);for(int i=0;i<3;i++)DeleteCam(ref fseGizmoVaos[i],ref fseGizmoVbos[i]);}
}
