using RE4_PS2_MOD_WORKSPACE.Core.Visual;
using OpenTK.Graphics.OpenGL4;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed partial class ScenarioViewport
{
    private const float ItaWorldScale=.01f;
    private ItaScene? itaScene;private EtmCatalog? itmCatalog;private bool itaGpuDirty=true,itaTexturesDirty=true;
    private int itaVao,itaVbo,itaCount,itaSelectedVao,itaSelectedVbo,itaSelectedCount,itaModelVao,itaModelVbo,itaModelCount,itaSelectedModelVao,itaSelectedModelVbo,itaSelectedModelCount;
    private readonly int[] itaGizmoVaos=new int[3],itaGizmoVbos=new int[3],itaGizmoCounts=new int[3];
    private readonly Dictionary<ItaTextureKey,int> glItaTextures=new();private readonly Dictionary<ItaTextureKey,bool> glItaTransparency=new();
    private readonly List<ItaDrawBatch> itaBatches=new(),itaSelectedBatches=new();private int selectedItaOrder=-1;
    private readonly Stack<Action> itaUndo=new();
    private ItaEntry? draggingIta;private ItaState itaDragStart;private Point itaDragMouse;private System.Numerics.Vector3 itaDragWorld;private int itaDragAxis;
    private bool itaGpuPreviewActive;private OpenTK.Mathematics.Matrix4 itaGpuPreviewModel=OpenTK.Mathematics.Matrix4.Identity;
    public bool ItaVisible{get;set;}=true;public EtsGizmoMode ItaTransformMode{get;set;}=EtsGizmoMode.Move;public bool IsItaDragging=>draggingIta!=null;
    public event Action<ItaEntry?>? ItaEntryClicked;public event Action<ItaEntry>? ItaEntryEdited;

    public void SetItaScene(ItaScene? scene,EtmCatalog? catalog){itaScene=scene;itmCatalog=catalog;selectedItaOrder=-1;itaUndo.Clear();itaGpuDirty=true;itaTexturesDirty=true;Invalidate();}
    public void SelectItaEntry(ItaEntry? entry){selectedItaOrder=entry?.FileOrder??-1;itaGpuDirty=true;Invalidate();}
    public void RefreshItaGeometry(ItaEntry? entry=null){if(entry!=null)selectedItaOrder=entry.FileOrder;itaGpuDirty=true;Invalidate();}
    public void FocusIta(ItaEntry? entry){if(entry==null)return;target=ItaWorld(entry);float radius=3f;if(itmCatalog?.ModelParts.TryGetValue(entry.ItemId,out var parts)==true){var points=parts.SelectMany(p=>p.Triangles).SelectMany(t=>new[]{TransformIta(t.A,entry),TransformIta(t.B,entry),TransformIta(t.C,entry)}).ToArray();if(points.Length>0){var min=points.Aggregate(new System.Numerics.Vector3(float.PositiveInfinity),System.Numerics.Vector3.Min);var max=points.Aggregate(new System.Numerics.Vector3(float.NegativeInfinity),System.Numerics.Vector3.Max);target=(min+max)*.5f;radius=Math.Max(1f,(max-min).Length()*.5f);}}distance=Math.Clamp(radius*2.8f,8f,5000f);cameraPosition=target-GetForward()*distance;Invalidate();}

    private void UploadIta()
    {
        itaGpuDirty=false;itaCount=itaSelectedCount=itaModelCount=itaSelectedModelCount=0;if(!glReady||itaScene==null)return;EnsureItaBuffers();
        var normal=new List<float>();var selected=new List<float>();var gizmos=new[]{new List<float>(),new List<float>(),new List<float>()};
        var models=new Dictionary<ItaTextureKey,List<float>>();var selectedModels=new Dictionary<ItaTextureKey,List<float>>();
        foreach(ItaEntry entry in itaScene.Entries)
        {
            bool isSelected=entry.FileOrder==selectedItaOrder;AddItaMarker(isSelected?selected:normal,entry,isSelected);if(isSelected&&entry.AppearanceType==0)AddItaGizmo(gizmos,entry);
            if(itmCatalog?.ModelParts.TryGetValue(entry.ItemId,out IReadOnlyList<EtmModelPart>? parts)==true)
                foreach(EtmModelPart part in parts)foreach(var material in part.Triangles.GroupBy(t=>t.TextureIndex))
                {var key=new ItaTextureKey(part.TextureFallback?.FileOrder??-1,material.Key);var buckets=isSelected?selectedModels:models;if(!buckets.TryGetValue(key,out List<float>? values)){values=new();buckets[key]=values;}AddItaModel(values,entry,material);}
        }
        UploadLineBuffer(itaVao,itaVbo,normal,out itaCount);UploadLineBuffer(itaSelectedVao,itaSelectedVbo,selected,out itaSelectedCount);
        for(int i=0;i<3;i++)UploadLineBuffer(itaGizmoVaos[i],itaGizmoVbos[i],gizmos[i],out itaGizmoCounts[i]);
        UploadEnemyModelBuffer(itaModelVao,itaModelVbo,BuildItaBatches(models,itaBatches),out itaModelCount);UploadEnemyModelBuffer(itaSelectedModelVao,itaSelectedModelVbo,BuildItaBatches(selectedModels,itaSelectedBatches),out itaSelectedModelCount);
    }
    private void EnsureItaBuffers(){if(itaVao==0)itaVao=GL.GenVertexArray();if(itaVbo==0)itaVbo=GL.GenBuffer();if(itaSelectedVao==0)itaSelectedVao=GL.GenVertexArray();if(itaSelectedVbo==0)itaSelectedVbo=GL.GenBuffer();if(itaModelVao==0)itaModelVao=GL.GenVertexArray();if(itaModelVbo==0)itaModelVbo=GL.GenBuffer();if(itaSelectedModelVao==0)itaSelectedModelVao=GL.GenVertexArray();if(itaSelectedModelVbo==0)itaSelectedModelVbo=GL.GenBuffer();for(int i=0;i<3;i++){if(itaGizmoVaos[i]==0)itaGizmoVaos[i]=GL.GenVertexArray();if(itaGizmoVbos[i]==0)itaGizmoVbos[i]=GL.GenBuffer();}}
    private void AddItaMarker(List<float> values,ItaEntry e,bool selected){var p=ItaWorld(e);float r=selected?1.8f:1.25f;void L(System.Numerics.Vector3 a,System.Numerics.Vector3 b)=>values.AddRange(new[]{a.X,a.Y,a.Z,0f,0f,0f,b.X,b.Y,b.Z,0f,0f,0f});L(p-new System.Numerics.Vector3(r,0,0),p+new System.Numerics.Vector3(r,0,0));L(p-new System.Numerics.Vector3(0,r,0),p+new System.Numerics.Vector3(0,r,0));L(p-new System.Numerics.Vector3(0,0,r),p+new System.Numerics.Vector3(0,0,r));}
    private void AddItaGizmo(List<float>[] axes,ItaEntry e){var p=ItaWorld(e);float length=CamScreenSize(p,72f);void L(int a,System.Numerics.Vector3 x,System.Numerics.Vector3 y)=>axes[a].AddRange(new[]{x.X,x.Y,x.Z,0f,0f,0f,y.X,y.Y,y.Z,0f,0f,0f});if(ItaTransformMode==EtsGizmoMode.Move){float head=length*.13f;for(int i=0;i<3;i++){var axis=i==0?System.Numerics.Vector3.UnitX:i==1?System.Numerics.Vector3.UnitY:System.Numerics.Vector3.UnitZ;var side=i==1?System.Numerics.Vector3.UnitX:System.Numerics.Vector3.UnitY;var end=p+axis*length;L(i,p,end);L(i,end,end-axis*head+side*head*.35f);L(i,end,end-axis*head-side*head*.35f);}}else{float radius=length*.76f;for(int i=0;i<3;i++)for(int n=0;n<48;n++){float a=n*MathF.Tau/48,b=(n+1)*MathF.Tau/48;System.Numerics.Vector3 A=i==0?new(0,MathF.Cos(a)*radius,MathF.Sin(a)*radius):i==1?new(MathF.Cos(a)*radius,0,MathF.Sin(a)*radius):new(MathF.Cos(a)*radius,MathF.Sin(a)*radius,0);System.Numerics.Vector3 B=i==0?new(0,MathF.Cos(b)*radius,MathF.Sin(b)*radius):i==1?new(MathF.Cos(b)*radius,0,MathF.Sin(b)*radius):new(MathF.Cos(b)*radius,MathF.Sin(b)*radius,0);L(i,p+A,p+B);}}}
    private void UploadItaGizmoOnly(){if(!glReady||draggingIta!=null)return;ItaEntry? entry=itaScene?.Entries.FirstOrDefault(x=>x.FileOrder==selectedItaOrder);if(entry==null||entry.AppearanceType!=0)return;EnsureItaBuffers();var axes=new[]{new List<float>(),new List<float>(),new List<float>()};AddItaGizmo(axes,entry);for(int i=0;i<3;i++)UploadLineBuffer(itaGizmoVaos[i],itaGizmoVbos[i],axes[i],out itaGizmoCounts[i]);}
    private void AddItaModel(List<float> values,ItaEntry e,IEnumerable<ScenarioTriangle> triangles){foreach(var t in triangles){var a=TransformIta(t.A,e);var b=TransformIta(t.B,e);var c=TransformIta(t.C,e);var n=System.Numerics.Vector3.Cross(b-a,c-a);float l=n.Length();if(!float.IsFinite(l)||l<.000001f)continue;n/=l;WriteEnemyModelVertex(values,a,n,FlipAssetUv(t.UvA));WriteEnemyModelVertex(values,b,n,FlipAssetUv(t.UvB));WriteEnemyModelVertex(values,c,n,FlipAssetUv(t.UvC));}}
    private System.Numerics.Vector3 TransformIta(System.Numerics.Vector3 v,ItaEntry e){if(MathF.Abs(e.RotationX)>.000001f){float c=MathF.Cos(e.RotationX),s=MathF.Sin(e.RotationX);v=new(v.X,v.Y*c-v.Z*s,v.Y*s+v.Z*c);}if(MathF.Abs(e.RotationY)>.000001f){float c=MathF.Cos(e.RotationY),s=MathF.Sin(e.RotationY);v=new(v.X*c+v.Z*s,v.Y,-v.X*s+v.Z*c);}if(MathF.Abs(e.RotationZ)>.000001f){float c=MathF.Cos(e.RotationZ),s=MathF.Sin(e.RotationZ);v=new(v.X*c-v.Y*s,v.X*s+v.Y*c,v.Z);}return v+ItaWorld(e);}
    private System.Numerics.Vector3 ItaWorld(ItaEntry e)
    {
        if(e.AppearanceType==2&&etsScene?.Entries.FirstOrDefault(x=>x.InstanceIndex==e.LinkedInstanceId) is EtsEntry obj)return EtsWorld(obj);
        if(e.AppearanceType==1&&eslScene?.Entries.FirstOrDefault(x=>x.Index==e.LinkedInstanceId) is EslEnemyEntry enemy)return EslToWorld(enemy);
        return e.Position*ItaWorldScale;
    }
    private static List<float> BuildItaBatches(Dictionary<ItaTextureKey,List<float>> buckets,List<ItaDrawBatch> batches){batches.Clear();var all=new List<float>();foreach(var p in buckets){int first=all.Count/8;all.AddRange(p.Value);if(p.Value.Count>0)batches.Add(new(p.Key,first,p.Value.Count/8));}return all;}
    private void DrawItaGpu(){var identity=OpenTK.Mathematics.Matrix4.Identity;GL.UniformMatrix4(uModel,true,ref identity);GL.UniformMatrix4(uNormalMatrix,true,ref identity);GL.Enable(EnableCap.DepthTest);GL.Disable(EnableCap.CullFace);GL.Uniform1(uUnlit,0);DrawItaModels(itaModelVao,itaModelCount,itaBatches);var preview=itaGpuPreviewActive?itaGpuPreviewModel:identity;GL.UniformMatrix4(uModel,true,ref preview);GL.UniformMatrix4(uNormalMatrix,true,ref preview);DrawItaModels(itaSelectedModelVao,itaSelectedModelCount,itaSelectedBatches);if(itaSelectedModelCount>0){GL.Uniform1(uUseTexture,0);GL.Uniform1(uUnlit,1);GL.Uniform3(uColor,1f,.72f,.08f);GL.Uniform1(uOpacity,.28f);GL.Enable(EnableCap.Blend);GL.BlendFunc(BlendingFactor.SrcAlpha,BlendingFactor.OneMinusSrcAlpha);GL.DepthMask(false);GL.Enable(EnableCap.PolygonOffsetFill);GL.PolygonOffset(-1f,-1f);GL.BindVertexArray(itaSelectedModelVao);GL.DrawArrays(PrimitiveType.Triangles,0,itaSelectedModelCount);GL.Disable(EnableCap.PolygonOffsetFill);GL.DepthMask(true);GL.Disable(EnableCap.Blend);GL.Uniform1(uOpacity,1f);}GL.UniformMatrix4(uModel,true,ref identity);GL.UniformMatrix4(uNormalMatrix,true,ref identity);GL.Uniform1(uUseTexture,0);GL.Uniform1(uUnlit,1);GL.Disable(EnableCap.DepthTest);GL.Uniform3(uColor,.95f,.35f,.75f);GL.BindVertexArray(itaVao);GL.LineWidth(3);GL.DrawArrays(PrimitiveType.Lines,0,itaCount);if(assetMeshSelection==null){GL.UniformMatrix4(uModel,true,ref preview);var colors=new[]{(1f,.16f,.12f),(.2f,.9f,.25f),(.15f,.48f,1f)};for(int i=0;i<3;i++){bool active=draggingIta!=null&&itaDragAxis==i+1;GL.Uniform3(uColor,active?1f:colors[i].Item1,active?1f:colors[i].Item2,active?.2f:colors[i].Item3);GL.BindVertexArray(itaGizmoVaos[i]);GL.LineWidth(active?8:5);GL.DrawArrays(PrimitiveType.Lines,0,itaGizmoCounts[i]);}GL.UniformMatrix4(uModel,true,ref identity);}GL.LineWidth(1);GL.Enable(EnableCap.DepthTest);GL.Enable(EnableCap.CullFace);GL.Uniform1(uOpacity,1f);}
    private void DrawItaModels(int vao,int count,List<ItaDrawBatch> batches){if(count==0)return;GL.BindVertexArray(vao);GL.Uniform3(uColor,.85f,.85f,.85f);foreach(var b in batches){if(glItaTextures.TryGetValue(b.Key,out int texture)){GL.Uniform1(uUseTexture,1);GL.BindTexture(TextureTarget.Texture2D,texture);}else GL.Uniform1(uUseTexture,0);GL.DrawArrays(PrimitiveType.Triangles,b.First,b.Count);}GL.BindTexture(TextureTarget.Texture2D,0);}
    private void UploadItaTextures(){itaTexturesDirty=false;foreach(int t in glItaTextures.Values)if(t!=0)GL.DeleteTexture(t);glItaTextures.Clear();glItaTransparency.Clear();if(itmCatalog==null)return;var reader=new Core.Textures.TplReader();var decoder=new Core.Textures.TextureDecoder();foreach(var parts in itmCatalog.ModelParts.Values)foreach(var part in parts){if(part.TextureFallback==null)continue;foreach(int index in part.Triangles.Select(x=>x.TextureIndex).Distinct())try{using var ms=new MemoryStream(part.TextureFallback.Data,false);using var br=new BinaryReader(ms);var tpl=reader.ReadTexture(br,index);ms.Position=0;using var bitmap=decoder.Decode(tpl,br);var key=new ItaTextureKey(part.TextureFallback.FileOrder,index);glItaTextures[key]=CreateEtsGlTexture(bitmap);glItaTransparency[key]=BitmapHasTransparency(bitmap);}catch{}}}
    private ItaEntry? PickIta(Point mouse){ItaEntry? hit=null;float best=float.PositiveInfinity;if(itaScene==null)return null;foreach(var e in itaScene.Entries){if(itmCatalog?.ModelParts.TryGetValue(e.ItemId,out var parts)==true)foreach(var part in parts)foreach(var triangle in part.Triangles){var a=TransformIta(triangle.A,e);var b=TransformIta(triangle.B,e);var c=TransformIta(triangle.C,e);if(!TryProjectWorldToScreen(a,out PointF pa)||!TryProjectWorldToScreen(b,out PointF pb)||!TryProjectWorldToScreen(c,out PointF pc)||!PointInScreenTriangle(mouse,pa,pb,pc))continue;float depth=System.Numerics.Vector3.DistanceSquared(cameraPosition,(a+b+c)/3f);if(depth<best){best=depth;hit=e;}}if(!TryProjectWorldToScreen(ItaWorld(e),out PointF p))continue;float d=(p.X-mouse.X)*(p.X-mouse.X)+(p.Y-mouse.Y)*(p.Y-mouse.Y);if(d<24*24&&d<best){best=d;hit=e;}}return hit;}
    private AssetMeshSelection? PickItaSurface(Point mouse,ItaEntry e){if(itmCatalog?.ModelParts.TryGetValue(e.ItemId,out var parts)!=true)return null;AssetMeshSelection? hit=null;float best=float.PositiveInfinity;for(int pi=0;pi<parts.Count;pi++)for(int ti=0;ti<parts[pi].Triangles.Count;ti++){var t=parts[pi].Triangles[ti];var p=new[]{TransformIta(t.A,e),TransformIta(t.B,e),TransformIta(t.C,e)};if(!TryProjectWorldToScreen(p[0],out PointF a)||!TryProjectWorldToScreen(p[1],out PointF b)||!TryProjectWorldToScreen(p[2],out PointF c)||!PointInScreenTriangle(mouse,a,b,c))continue;float depth=System.Numerics.Vector3.DistanceSquared(cameraPosition,(p[0]+p[1]+p[2])/3);if(depth>=best)continue;best=depth;int element=0;var position=(p[0]+p[1]+p[2])/3;if(AssetSelectionMode==AssetMeshSelectionMode.Vertex){var q=new[]{a,b,c};element=Enumerable.Range(0,3).OrderBy(i=>(q[i].X-mouse.X)*(q[i].X-mouse.X)+(q[i].Y-mouse.Y)*(q[i].Y-mouse.Y)).First();position=p[element];}else if(AssetSelectionMode==AssetMeshSelectionMode.Edge){var q=new[]{a,b,c};element=Enumerable.Range(0,3).OrderBy(i=>DistancePointToSegment(mouse,q[i],q[(i+1)%3])).First();position=(p[element]+p[(element+1)%3])/2;}hit=new(AssetSelectionMode,pi,ti,element,position);}return hit;}
    private int PickItaAxis(Point mouse,ItaEntry e){var p=ItaWorld(e);float best=11;int result=0;float length=CamScreenSize(p,72f);if(ItaTransformMode==EtsGizmoMode.Move){if(!TryProjectWorldToScreen(p,out PointF a))return 0;var ends=new[]{p+System.Numerics.Vector3.UnitX*length,p+System.Numerics.Vector3.UnitY*length,p+System.Numerics.Vector3.UnitZ*length};for(int i=0;i<3;i++)if(TryProjectWorldToScreen(ends[i],out PointF b)){float d=DistancePointToSegment(mouse,a,b);if(d<best){best=d;result=i+1;}}}else{float radius=length*.76f;for(int axis=0;axis<3;axis++)for(int n=0;n<48;n++){float q=n*MathF.Tau/48,r=(n+1)*MathF.Tau/48;System.Numerics.Vector3 P(float v)=>axis==0?new(0,MathF.Cos(v)*radius,MathF.Sin(v)*radius):axis==1?new(MathF.Cos(v)*radius,0,MathF.Sin(v)*radius):new(MathF.Cos(v)*radius,MathF.Sin(v)*radius,0);if(TryProjectWorldToScreen(p+P(q),out PointF a)&&TryProjectWorldToScreen(p+P(r),out PointF b)){float d=DistancePointToSegment(mouse,a,b);if(d<best){best=d;result=axis+1;}}}}return result;}
    private bool TryBeginItaDrag(Point mouse){if(assetMeshSelection!=null||AssetMeshEditingEnabled&&AssetSelectionMode==AssetMeshSelectionMode.Object)return false;ItaEntry? e=itaScene?.Entries.FirstOrDefault(x=>x.FileOrder==selectedItaOrder);if(e==null||e.AppearanceType!=0)return false;int axis=PickItaAxis(mouse,e);if(axis==0&&!ReferenceEquals(PickIta(mouse),e))return false;draggingIta=e;itaDragStart=ItaState.From(e);itaDragMouse=mouse;itaDragWorld=ItaWorld(e);itaDragAxis=axis==0?(ItaTransformMode==EtsGizmoMode.Move?7:2):axis;itaGpuPreviewActive=true;itaGpuPreviewModel=OpenTK.Mathematics.Matrix4.Identity;return true;}
    private void UpdateItaDrag(Point mouse){if(draggingIta==null)return;int dx=mouse.X-itaDragMouse.X,dy=mouse.Y-itaDragMouse.Y;if(ItaTransformMode==EtsGizmoMode.Move){if(itaDragAxis is 1 or 3 or 7&&TryScreenPointOnHorizontalPlane(itaDragMouse,itaDragWorld.Y,out var a)&&TryScreenPointOnHorizontalPlane(mouse,itaDragWorld.Y,out var b)){var d=(b-a)/ItaWorldScale;if(itaDragAxis is 1 or 7)draggingIta.PositionX=itaDragStart.Px+d.X;if(itaDragAxis is 3 or 7)draggingIta.PositionZ=itaDragStart.Pz+d.Z;}else if(itaDragAxis==2){float depth=Math.Max(.05f,System.Numerics.Vector3.Dot(itaDragWorld-cameraPosition,GetForward()));Rectangle viewport=GetRenderViewport();float aspect=Math.Max(.01f,viewport.Width/(float)Math.Max(1,viewport.Height));float verticalFov=FieldOfViewIsHorizontal?2f*MathF.Atan(MathF.Tan(fieldOfViewDegrees*MathF.PI/360f)/aspect):fieldOfViewDegrees*MathF.PI/180f;float worldPerPixel=2f*depth*MathF.Tan(verticalFov*.5f)/Math.Max(1,viewport.Height);draggingIta.PositionY=itaDragStart.Py-dy*worldPerPixel/ItaWorldScale;}itaGpuPreviewModel=OpenTK.Mathematics.Matrix4.CreateTranslation((draggingIta.PositionX-itaDragStart.Px)*ItaWorldScale,(draggingIta.PositionY-itaDragStart.Py)*ItaWorldScale,(draggingIta.PositionZ-itaDragStart.Pz)*ItaWorldScale);}else{float d=dx*MathF.PI/360;if(itaDragAxis==1)draggingIta.RotationX=itaDragStart.Rx+d;else if(itaDragAxis==3)draggingIta.RotationZ=itaDragStart.Rz+d;else draggingIta.RotationY=itaDragStart.Ry+d;var pivot=new OpenTK.Mathematics.Vector3(itaDragWorld.X,itaDragWorld.Y,itaDragWorld.Z);var axis=itaDragAxis==1?OpenTK.Mathematics.Vector3.UnitX:itaDragAxis==3?OpenTK.Mathematics.Vector3.UnitZ:OpenTK.Mathematics.Vector3.UnitY;itaGpuPreviewModel=OpenTK.Mathematics.Matrix4.CreateTranslation(-pivot)*OpenTK.Mathematics.Matrix4.CreateFromAxisAngle(axis,d)*OpenTK.Mathematics.Matrix4.CreateTranslation(pivot);}Invalidate();}
    private void EndItaDrag(){ItaEntry? edited=draggingIta;ItaState before=itaDragStart;draggingIta=null;itaDragAxis=0;itaGpuPreviewActive=false;itaGpuPreviewModel=OpenTK.Mathematics.Matrix4.Identity;itaGpuDirty=true;if(edited!=null){ItaState after=ItaState.From(edited);if(!before.Equals(after)){itaUndo.Push(()=>{before.Apply(edited);selectedItaOrder=edited.FileOrder;itaGpuDirty=true;ItaEntryEdited?.Invoke(edited);ItaEntryClicked?.Invoke(edited);Invalidate();});while(itaUndo.Count>100){var keep=itaUndo.Reverse().Take(100).Reverse().ToArray();itaUndo.Clear();foreach(var action in keep)itaUndo.Push(action);}}ItaEntryEdited?.Invoke(edited);}Invalidate();}
    public bool UndoItaEdit(){if(itaUndo.Count==0)return false;itaUndo.Pop()();return true;}
    private readonly record struct ItaState(float Px,float Py,float Pz,float Rx,float Ry,float Rz){public static ItaState From(ItaEntry e)=>new(e.PositionX,e.PositionY,e.PositionZ,e.RotationX,e.RotationY,e.RotationZ);public void Apply(ItaEntry e){e.PositionX=Px;e.PositionY=Py;e.PositionZ=Pz;e.RotationX=Rx;e.RotationY=Ry;e.RotationZ=Rz;}}
    private readonly record struct ItaTextureKey(int Source,int Texture);private readonly record struct ItaDrawBatch(ItaTextureKey Key,int First,int Count);
}
