using RE4_PS2_MOD_WORKSPACE.Core.Collision;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed record CollisionPrimitiveOptions(EsatKind TargetKind,string Kind,System.Numerics.Vector3 Dimensions);
public sealed class CollisionPrimitiveDialog : AppForm
{
    private readonly ComboBox target=new(){Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};private readonly ComboBox kind=new(){Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};private readonly ComboBox preset=new(){Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};private readonly NumericUpDown width=new(){Dock=DockStyle.Fill,Minimum=.1M,Maximum=1000,DecimalPlaces=2,Increment=.25M};private readonly NumericUpDown height=new(){Dock=DockStyle.Fill,Minimum=.02M,Maximum=1000,DecimalPlaces=2,Increment=.1M};private readonly NumericUpDown depth=new(){Dock=DockStyle.Fill,Minimum=.1M,Maximum=1000,DecimalPlaces=2,Increment=.25M};public CollisionPrimitiveOptions? Options{get;private set;}
    public CollisionPrimitiveDialog(){Text="Criar colisão SAT/EAT";StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=MinimizeBox=false;ShowInTaskbar=false;ClientSize=new Size(390,372);BackColor=Color.FromArgb(18,21,27);ForeColor=Color.White;Font=new Font("Segoe UI",9F);target.Items.AddRange(new object[]{"SAT","EAT"});target.SelectedIndex=0;kind.Items.AddRange(new object[]{"Plano de chão","Cubo","Prisma triangular","Prisma triangular completo","Parede","Plataforma"});kind.SelectedIndex=0;preset.Items.AddRange(new object[]{"2 m","5 m","10 m","20 m","Personalizado"});preset.SelectedIndex=2;var grid=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18),ColumnCount=2,RowCount=8};grid.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,110));grid.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));AddRow(grid,0,"DESTINO",target);AddRow(grid,1,"TIPO",kind);AddRow(grid,2,"PREDEFINIÇÃO",preset);AddRow(grid,3,"LARGURA (m)",width);AddRow(grid,4,"ALTURA (m)",height);AddRow(grid,5,"PROFUNDIDADE (m)",depth);var hint=new Label{Dock=DockStyle.Fill,Text="O objeto será criado à frente da câmera.",ForeColor=Color.FromArgb(145,155,173),TextAlign=ContentAlignment.MiddleLeft};grid.Controls.Add(hint,0,6);grid.SetColumnSpan(hint,2);var create=new Button{Text="＋  CRIAR",Dock=DockStyle.Fill,BackColor=Color.FromArgb(206,54,62),ForeColor=Color.White,FlatStyle=FlatStyle.Flat};create.FlatAppearance.BorderSize=0;create.Click+=(_,_)=>{Options=new(target.SelectedIndex==1?EsatKind.Eat:EsatKind.Sat,kind.Text,new((float)width.Value*100f,(float)height.Value*100f,(float)depth.Value*100f));DialogResult=DialogResult.OK;Close();};grid.Controls.Add(create,0,7);grid.SetColumnSpan(create,2);Controls.Add(grid);AcceptButton=create;kind.SelectedIndexChanged+=(_,_)=>ApplyPreset();preset.SelectedIndexChanged+=(_,_)=>ApplyPreset();ApplyPreset();}
    private void ApplyPreset(){if(preset.SelectedIndex<0||preset.SelectedIndex==4)return;decimal size=preset.SelectedIndex switch{0=>2,1=>5,2=>10,_=>20};switch(kind.Text){case "Plano de chão":width.Value=size*2;height.Value=.1M;depth.Value=size*2;break;case "Prisma triangular":case "Prisma triangular completo":width.Value=size*2;height.Value=size;depth.Value=size*2;break;case "Parede":width.Value=size*2;height.Value=size;depth.Value=Math.Max(.2M,size*.1M);break;case "Plataforma":width.Value=size*2;height.Value=Math.Max(.2M,size*.1M);depth.Value=size*2;break;default:width.Value=height.Value=depth.Value=size;break;}}
    private static void AddRow(TableLayoutPanel grid,int row,string label,Control control){grid.RowStyles.Add(new RowStyle(SizeType.Absolute,42));grid.Controls.Add(new Label{Text=label,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft,ForeColor=Color.FromArgb(145,155,173),Font=new Font("Segoe UI Semibold",8F)},0,row);grid.Controls.Add(control,1,row);}
}