using RE4_PS2_MOD_WORKSPACE.Core.Visual;
namespace RE4_PS2_MOD_WORKSPACE;

public sealed class EnemyQuickAdjustmentsDialog : AppForm
{
    private static readonly Color Bg=Color.FromArgb(14,17,22),Card=Color.FromArgb(25,29,37),Card2=Color.FromArgb(34,39,49),Muted=Color.FromArgb(151,160,176),Accent=Color.FromArgb(211,55,67);
    private readonly ComboBox files=new(),scenario=new(),hpMode=new(),hpPreset=new(),fullPreset=new(),scaleMin=new(),scaleMax=new();private readonly NumericUpDown hp=new();private readonly CheckBox activeOnly=new(),randomWeapons=new(),randomEquipment=new(),randomScale=new();private readonly TextBox seed=new();
    private readonly Label editCountSummary=new(){Left=28,Top=651,Width=430,Height=24,ForeColor=Muted};
    public bool AllFiles=>files.SelectedItem is FileChoice { IsAll:true };public IReadOnlyList<string> SelectedFiles=>files.SelectedItem is FileChoice { IsAll:true }?fileChoices.Where(x=>!x.IsAll).Select(x=>x.Path!).ToArray():files.SelectedItem is FileChoice choice?new[]{choice.Path!}:Array.Empty<string>();public EnemyQuickAdjustmentOptions? Options{get;private set;}public bool HasExtractedFiles=>fileChoices.Any(x=>!x.IsAll);
    private readonly List<FileChoice> fileChoices=new();private readonly Dictionary<string,IReadOnlyList<(byte Stage,byte Room,byte Active)>> locationsByFile;
    public EnemyQuickAdjustmentsDialog(string currentFile,IReadOnlyList<string> extractedFiles,IReadOnlyDictionary<string,IReadOnlyList<(byte Stage,byte Room,byte Active)>> locationsByFile)
    {
        this.locationsByFile=new Dictionary<string,IReadOnlyList<(byte Stage,byte Room,byte Active)>>(locationsByFile,StringComparer.OrdinalIgnoreCase);
        Text="Ajustes rápidos de inimigos";StartPosition=FormStartPosition.CenterParent;FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=MinimizeBox=false;ShowInTaskbar=false;ClientSize=new(790,720);BackColor=Bg;ForeColor=Color.White;Font=new("Segoe UI",9F);
        Controls.Add(new Label{Text="AJUSTES RÁPIDOS",Left=26,Top=20,Width=500,Height=30,Font=new("Segoe UI Semibold",16F),ForeColor=Color.White});Controls.Add(new Label{Text="HP por faixa, dificuldade completa e aleatoriedade reproduzível.",Left=28,Top=53,Width=700,Height=24,ForeColor=Muted});AddTarget(currentFile,extractedFiles);AddDifficulty();AddRandom();Controls.Add(editCountSummary);var apply=Button("APLICAR AJUSTES",Accent,486,648,135);apply.Click+=(_,_)=>AcceptOptions();Controls.Add(apply);var cancel=Button("CANCELAR",Card2,631,648,135);cancel.Click+=(_,_)=>{DialogResult=DialogResult.Cancel;Close();};Controls.Add(cancel);CancelButton=cancel;AcceptButton=apply;RefreshEditCountSummary();
    }
    private void AddTarget(string current,IReadOnlyList<string> extractedFiles){Panel p=PanelAt(24,88,742,112,"ALVO");LabelAt(p,"Emleon extraído",18,43);Combo(files,130,38,265);foreach(string path in extractedFiles.Distinct(StringComparer.OrdinalIgnoreCase).OrderBy(Path.GetFileName)){var choice=new FileChoice(path,Path.GetFileName(path),false);fileChoices.Add(choice);files.Items.Add(choice);}var all=new FileChoice(null,"Todos os emleon extraídos",true);fileChoices.Add(all);files.Items.Add(all);int selected=fileChoices.FindIndex(x=>!x.IsAll&&string.Equals(Path.GetFileName(x.Path),current,StringComparison.OrdinalIgnoreCase));files.SelectedIndex=files.Items.Count>0?(selected>=0?selected:0):-1;p.Controls.Add(files);LabelAt(p,"Cenário",420,43);Combo(scenario,485,38,225);files.SelectedIndexChanged+=FilesSelectionChanged;scenario.SelectedIndexChanged+=(_,_)=>RefreshEditCountSummary();p.Controls.Add(scenario);activeOnly.Text="Alterar somente inimigos ativos";activeOnly.Checked=true;activeOnly.AutoSize=true;activeOnly.SetBounds(18,78,260,24);activeOnly.ForeColor=Color.Gainsboro;p.Controls.Add(activeOnly);activeOnly.CheckedChanged+=(_,_)=>RefreshEditCountSummary();RefreshScenarioChoices();}
    private void RefreshScenarioChoices(){var previous=scenario.SelectedItem as Scope;var available=SelectedFiles.Where(locationsByFile.ContainsKey).SelectMany(x=>locationsByFile[x]).Where(x=>x.Stage!=0||x.Room!=0).Select(x=>(x.Stage,x.Room)).Distinct().OrderBy(x=>x.Stage).ThenBy(x=>x.Room).ToArray();scenario.BeginUpdate();try{scenario.Items.Clear();scenario.Items.Add(new Scope(null,null,"Todos os cenários"));foreach(var x in available)scenario.Items.Add(new Scope(x.Stage,x.Room,$"r{x.Stage:X1}{x.Room:X2}"));int idx=0;if(previous?.Stage is byte ps&&previous.Room is byte pr)for(int i=1;i<scenario.Items.Count;i++)if(scenario.Items[i] is Scope sc&&sc.Stage==ps&&sc.Room==pr){idx=i;break;}scenario.SelectedIndex=Math.Clamp(idx,0,scenario.Items.Count-1);}finally{scenario.EndUpdate();}RefreshEditCountSummary();}
    private void FilesSelectionChanged(object? sender,EventArgs e)=>RefreshScenarioChoices();
    private void RefreshEditCountSummary(){if(editCountSummary.IsDisposed)return;Scope? selectedScenario=scenario.SelectedItem as Scope;bool allScenarios=selectedScenario?.Stage==null;int matched=0;foreach(string path in SelectedFiles){if(!locationsByFile.TryGetValue(path,out var entries))continue;matched+=entries.Count(x=>(x.Stage!=0||x.Room!=0)&&(!activeOnly.Checked||x.Active!=0)&&(allScenarios||x.Stage==selectedScenario!.Stage&&x.Room==selectedScenario.Room));}editCountSummary.Text=$"{matched:N0} entry(s) serão editadas • HP máximo: {short.MaxValue:N0}";}
    private void AddDifficulty(){Panel p=PanelAt(24,212,742,204,"VIDA E DIFICULDADE");LabelAt(p,"Modo de HP",18,45);Combo(hpMode,112,39,180);hpMode.Items.AddRange(new object[]{"Não alterar HP","HP fixo para todos","Usar preset de HP"});hpMode.SelectedIndex=0;p.Controls.Add(hpMode);LabelAt(p,"Valor fixo",320,45);hp.SetBounds(390,39,120,28);hp.Minimum=100;hp.Maximum=short.MaxValue;hp.Increment=100;hp.Value=1000;hp.BackColor=Card2;hp.ForeColor=Color.White;hp.Enabled=false;p.Controls.Add(hp);LabelAt(p,"Preset somente de HP",18,96);Combo(hpPreset,160,90,550);FillPresets(hpPreset,false);hpPreset.Enabled=false;p.Controls.Add(hpPreset);LabelAt(p,"Preset completo",18,147);Combo(fullPreset,160,141,550);FillPresets(fullPreset,true);p.Controls.Add(fullPreset);hpMode.SelectedIndexChanged+=(_,_)=>{hp.Enabled=hpMode.SelectedIndex==1;hpPreset.Enabled=hpMode.SelectedIndex==2;if(hpMode.SelectedIndex!=2)hpPreset.SelectedIndex=0;};hpPreset.SelectedIndexChanged+=(_,_)=>{if(hpPreset.SelectedIndex>0){hpMode.SelectedIndex=2;fullPreset.SelectedIndex=0;}};fullPreset.SelectedIndexChanged+=(_,_)=>{if(fullPreset.SelectedIndex>0){hpMode.SelectedIndex=0;hpPreset.SelectedIndex=0;}};}
    private void AddRandom(){Panel p=PanelAt(24,428,742,188,"ALEATORIEDADE REPRODUZÍVEL");randomWeapons.Text="Armas";randomEquipment.Text="Acessórios/equipamentos";randomScale.Text="Tamanhos";int x=18;foreach(var c in new[]{randomWeapons,randomEquipment,randomScale}){c.AutoSize=true;c.Left=x;c.Top=43;c.ForeColor=Color.Gainsboro;p.Controls.Add(c);x+=c.Width+28;}LabelAt(p,"Tamanho mínimo",18,83);Combo(scaleMin,122,77,115);FillScales(scaleMin,1);p.Controls.Add(scaleMin);LabelAt(p,"Máximo",270,83);Combo(scaleMax,330,77,115);FillScales(scaleMax,4);p.Controls.Add(scaleMax);LabelAt(p,"Semente",18,127);seed.SetBounds(82,121,500,30);seed.BackColor=Card2;seed.ForeColor=Color.White;seed.BorderStyle=BorderStyle.FixedSingle;seed.Text=Guid.NewGuid().ToString("N")[..12];p.Controls.Add(seed);var regenerate=Button("NOVA",Card2,594,120,110);regenerate.Click+=(_,_)=>seed.Text=Guid.NewGuid().ToString("N")[..12];p.Controls.Add(regenerate);}
    private void AcceptOptions(){if(SelectedFiles.Count==0){MessageBox.Show(this,"Nenhum emleon extraído foi encontrado. Extraia um arquivo ESL antes de aplicar os ajustes.","Ajustes rápidos",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}var s=scenario.SelectedItem as Scope;bool complete=fullPreset.SelectedIndex>0;EnemyQuickDifficulty d=Parse(complete?fullPreset.SelectedItem:hpPreset.SelectedItem);Options=new(!complete&&hpMode.SelectedIndex==1,(int)hp.Value,d,complete,randomWeapons.Checked,randomEquipment.Checked,randomScale.Checked,((ScaleChoice)scaleMin.SelectedItem!).Raw,((ScaleChoice)scaleMax.SelectedItem!).Raw,string.IsNullOrWhiteSpace(seed.Text)?"re4":seed.Text.Trim(),activeOnly.Checked,s?.Stage,s?.Room);DialogResult=DialogResult.OK;Close();}
    private static void FillPresets(ComboBox c,bool full){c.Items.Add("Nenhum");string[] names={"Fácil • 500–1.000 HP","Normal • 1.000–2.000 HP","Difícil • 2.500–5.000 HP","Profissional • 5.000–8.000 HP","Brutal • 8.000–14.000 HP","Pesadelo • 14.000–20.000 HP","Impossível • 20.000–30.000 HP"};foreach(string n in names)c.Items.Add(full?n+" + visão e inimigos armados":n);c.SelectedIndex=0;}
    private static EnemyQuickDifficulty Parse(object? v){string s=v?.ToString()??"";if(s.StartsWith("Fácil"))return EnemyQuickDifficulty.Facil;if(s.StartsWith("Normal"))return EnemyQuickDifficulty.Normal;if(s.StartsWith("Difícil"))return EnemyQuickDifficulty.Dificil;if(s.StartsWith("Profissional"))return EnemyQuickDifficulty.Profissional;if(s.StartsWith("Brutal"))return EnemyQuickDifficulty.Brutal;if(s.StartsWith("Pesadelo"))return EnemyQuickDifficulty.Pesadelo;if(s.StartsWith("Impossível"))return EnemyQuickDifficulty.Impossivel;return EnemyQuickDifficulty.Nenhum;}
    private static void FillScales(ComboBox c,int selected){foreach(var x in new[]{new ScaleChoice(8,"0,50×"),new ScaleChoice(12,"0,75×"),new ScaleChoice(16,"1,00×"),new ScaleChoice(20,"1,25×"),new ScaleChoice(24,"1,50×"),new ScaleChoice(32,"2,00×"),new ScaleChoice(40,"2,50×"),new ScaleChoice(48,"3,00×")})c.Items.Add(x);c.SelectedIndex=selected;}
    private Panel PanelAt(int x,int y,int w,int h,string title){var p=new Panel{Left=x,Top=y,Width=w,Height=h,BackColor=Card};p.Controls.Add(new Label{Text=title,Left=18,Top=13,Width=w-36,Height=20,ForeColor=Color.FromArgb(220,225,234),Font=new("Segoe UI Semibold",9F)});Controls.Add(p);return p;}private static void LabelAt(Control p,string text,int x,int y)=>p.Controls.Add(new Label{Text=text,Left=x,Top=y,AutoSize=true,ForeColor=Muted});private static void Combo(ComboBox c,int x,int y,int w){c.SetBounds(x,y,w,30);c.DropDownStyle=ComboBoxStyle.DropDownList;c.BackColor=Card2;c.ForeColor=Color.White;c.FlatStyle=FlatStyle.Flat;}private static Button Button(string text,Color color,int x,int y,int w)=>new(){Text=text,Left=x,Top=y,Width=w,Height=34,BackColor=color,ForeColor=Color.White,FlatStyle=FlatStyle.Flat};private sealed record Scope(byte? Stage,byte? Room,string Label){public override string ToString()=>Label;}private sealed record ScaleChoice(int Raw,string Label){public override string ToString()=>Label;}private sealed record FileChoice(string? Path,string Label,bool IsAll){public override string ToString()=>Label;}
}
