using RE4_PS2_MOD_WORKSPACE.Core.Iso;
namespace RE4_PS2_MOD_WORKSPACE.Core.Executable;
public enum ExecutableRegion{Slus,Sles,DebugSlps}
public sealed class Ps2ExecutableDocument{
public const int IsoElfOffset=0x8B000;private readonly byte[] original;private byte[] data;
public string FilePath{get;}public string? IsoPath{get;}public long IsoOffset{get;}public bool IsIso=>IsoPath!=null;public string SourceDisplay=>IsIso?$"{Path.GetFileName(IsoPath)}  ›  {Path.GetFileName(FilePath)}":Path.GetFileName(FilePath);public ExecutableRegion Region{get;}public string ProductCode=>Region switch{ExecutableRegion.Slus=>"SLUS-21134",ExecutableRegion.Sles=>"SLES-53702",_=>"SLPS-00000 DEBUG"};public bool IsModified=>!data.AsSpan().SequenceEqual(original);
private Ps2ExecutableDocument(string p,ExecutableRegion r,byte[] b,string? iso=null,long isoOffset=0){FilePath=p;Region=r;data=b;original=(byte[])b.Clone();IsoPath=iso;IsoOffset=isoOffset;}
public static Ps2ExecutableDocument Open(string p){byte[] b=File.ReadAllBytes(p);if(b.Length<52||b[0]!=0x7F||b[1]!=(byte)'E'||b[2]!=(byte)'L'||b[3]!=(byte)'F')throw new InvalidDataException("O arquivo selecionado não é um ELF.");if(b[4]!=1||b[5]!=1||BitConverter.ToUInt16(b,18)!=8)throw new InvalidDataException("O arquivo não é um ELF32 MIPS little-endian compatível.");var r=b.Length switch{0x2F413C=>ExecutableRegion.Slus,0x2F43BC=>ExecutableRegion.Sles,0x23FBC20=>ExecutableRegion.DebugSlps,_=>Detect(b)};return new(p,r,b);}
public static Ps2ExecutableDocument OpenIso(string isoPath){var entries=Iso9660Reader.ReadAllFiles(isoPath);var candidates=entries.Where(x=>!x.IsDirectory&&(x.Name.StartsWith("SLUS_",StringComparison.OrdinalIgnoreCase)||x.Name.StartsWith("SLES_",StringComparison.OrdinalIgnoreCase)||x.Name.StartsWith("SLPS_",StringComparison.OrdinalIgnoreCase)||x.Name.EndsWith(".ELF",StringComparison.OrdinalIgnoreCase))).ToArray();foreach(var entry in candidates){try{byte[] b=new byte[checked((int)entry.Size)];using var fs=new FileStream(isoPath,FileMode.Open,FileAccess.Read,FileShare.ReadWrite);fs.Position=entry.DataOffset;fs.ReadExactly(b);return OpenBytes(entry.FullPath,b,isoPath,entry.DataOffset);}catch(InvalidDataException){}}throw new InvalidDataException("Nenhum executável SLUS, SLES ou SLPS compatível foi encontrado dentro da ISO.");}
private static Ps2ExecutableDocument OpenBytes(string name,byte[] b,string iso,long offset){if(b.Length<52||b[0]!=0x7F||b[1]!=(byte)'E'||b[2]!=(byte)'L'||b[3]!=(byte)'F')throw new InvalidDataException();if(b[4]!=1||b[5]!=1||BitConverter.ToUInt16(b,18)!=8)throw new InvalidDataException();var r=b.Length switch{0x2F413C=>ExecutableRegion.Slus,0x2F43BC=>ExecutableRegion.Sles,0x23FBC20=>ExecutableRegion.DebugSlps,_=>Detect(b)};return new(name,r,b,iso,offset);}
private static ExecutableRegion Detect(byte[] b){string s=System.Text.Encoding.ASCII.GetString(b);if(s.Contains("BASLUS-21134"))return ExecutableRegion.Slus;if(s.Contains("BASLES-53702"))return ExecutableRegion.Sles;if(s.Contains("SLPS_000.00")||s.Contains("SLPS-00000"))return ExecutableRegion.DebugSlps;throw new InvalidDataException("A região não foi reconhecida. São aceitos SLUS_211.34, SLES_537.02 e a build final de debug SLPS_000.00.");}
public ushort U16(int o){Check(o,2);return BitConverter.ToUInt16(data,o);}public byte U8(int o){Check(o,1);return data[o];}public float F32(int o){Check(o,4);return BitConverter.ToSingle(data,o);}
public void U16(int o,decimal v){Check(o,2);BitConverter.GetBytes(checked((ushort)v)).CopyTo(data,o);}public void U8(int o,decimal v){Check(o,1);data[o]=checked((byte)v);}public void F32(int o,decimal v){Check(o,4);BitConverter.GetBytes((float)v).CopyTo(data,o);}public void Revert()=>data=(byte[])original.Clone();
public byte[] ReadBytes(int o,int count){Check(o,count);return data.AsSpan(o,count).ToArray();}public void WriteBytes(int o,ReadOnlySpan<byte> value){Check(o,value.Length);value.CopyTo(data.AsSpan(o,value.Length));}
public void Save(bool createIsoBackup=true){if(!IsModified)return;if(IsIso){string bak=IsoPath!+".bak";if(createIsoBackup&&!File.Exists(bak))File.Copy(IsoPath!,bak);using var fs=new FileStream(IsoPath!,FileMode.Open,FileAccess.ReadWrite,FileShare.None);if(IsoOffset<0||IsoOffset+data.Length>fs.Length)throw new InvalidDataException("A área do ELF ultrapassa os limites da ISO.");byte[] current=new byte[data.Length];fs.Position=IsoOffset;fs.ReadExactly(current);if(!current.AsSpan().SequenceEqual(original))throw new IOException("O ELF dentro da ISO foi alterado por outro processo. Reabra a ISO antes de salvar.");fs.Position=IsoOffset;fs.Write(data);fs.Flush(true);}else{string bak=FilePath+".bak";if(!File.Exists(bak))File.Copy(FilePath,bak);string tmp=FilePath+".tmp";File.WriteAllBytes(tmp,data);File.Move(tmp,FilePath,true);}Buffer.BlockCopy(data,0,original,0,data.Length);}private void Check(int o,int n){if(o<0||o+n>data.Length)throw new InvalidDataException($"Offset inválido: 0x{o:X}");}}
public static class Ps2ExecutableMap{
private static int E(int iso)=>iso-Ps2ExecutableDocument.IsoElfOffset;
private static readonly string[] CapNames={"Handgun","Handgun com silenciador","Red9","Red9 com coronha","Matilda","Punisher","Punisher (medalhões)","Blacktail","Broken Butterfly","Shotgun","Striker","Rifle","Rifle com mira","Rifle infravermelho","Rifle semiautomático","Semiautomático com mira","Semiautomático infravermelho","TMP","TMP com coronha","Mine Thrower","Mine Thrower com mira","Killer7","Chicago Typewriter","Rocket Launcher","Rocket Launcher especial","Rocket Launcher infinito","Handcannon","Faca","Granada explosiva","Granada incendiária","Granada de luz","Ovo branco","Ovo marrom","Ovo dourado","Riot Gun","Arco do Krauser","TMP do HUNK","P.R.L. 412","Bowgun da Ada","Shotgun da Ada","Chicago da Ada"};
public static IReadOnlyList<(string Name,int Offset)> Capacity(ExecutableRegion r){int start=r switch{ExecutableRegion.Slus=>0x3359C0,ExecutableRegion.Sles=>0x335C40,_=>0};if(r==ExecutableRegion.DebugSlps){var debug=new List<(string,int)>();for(int i=0;i<CapNames.Length;i++){int n=i;if(i>=31)n++;if(i>=38)n++;debug.Add((CapNames[i],0x2EC820+n*0x16));}return debug;}var x=new List<(string,int)>();for(int i=0;i<CapNames.Length;i++){int n=i;if(i>=31)n++;if(i>=38)n++;x.Add((CapNames[i],E(start+n*0x16)));}return x;}
private static IReadOnlyList<(string Name,int Offset)> T(ExecutableRegion r,int us,int eu,int debug,string[] n,int stride)=>n.Select((s,i)=>(s,r==ExecutableRegion.DebugSlps?debug+i*stride:E((r==ExecutableRegion.Slus?us:eu)+i*stride))).ToArray();
public static IReadOnlyList<(string Name,int Offset)> Damage(ExecutableRegion r)=>T(r,0x2AD76C,0x2AD9EC,0x2612EC,new[]{"Punisher","Handgun","Red9","Blacktail","Broken Butterfly","Killer7","Shotgun","Striker","Rifle","Rifle semiautomático","TMP","Chicago Typewriter"},0x1C).Concat(new[]{("Handcannon",r==ExecutableRegion.DebugSlps?0x261474:E(r==ExecutableRegion.Slus?0x2AD8F4:0x2ADB74)),("Matilda",r==ExecutableRegion.DebugSlps?0x2614AC:E(r==ExecutableRegion.Slus?0x2AD92C:0x2ADBAC)),("Riot Gun",r==ExecutableRegion.DebugSlps?0x26166C:E(r==ExecutableRegion.Slus?0x2ADAEC:0x2ADD6C))}).ToArray();
public static IReadOnlyList<(string Name,int Offset)> Reload(ExecutableRegion r){string[] n={"Punisher","Handgun","Red9","Blacktail","Broken Butterfly","Killer7","Shotgun","Striker","Rifle","Rifle semiautomático","TMP","Chicago Typewriter"};var v=T(r,0x34B344,0x34B5E4,0x31A3E4,n,0x0C).ToList();int d=r==ExecutableRegion.Slus?0:0x2A0;v.AddRange(new[]{("Mine Thrower",r==ExecutableRegion.DebugSlps?0x31A480:E(0x34B3E0+d)),("Handcannon",r==ExecutableRegion.DebugSlps?0x31A48C:E(0x34B3EC+d)),("Matilda",r==ExecutableRegion.DebugSlps?0x31A4A4:E(0x34B404+d)),("Riot Gun",r==ExecutableRegion.DebugSlps?0x31A564:E(0x34B4C4+d)),("Bowgun da Ada",r==ExecutableRegion.DebugSlps?0x31A618:E(0x34B578+d))});return v;}
public static IReadOnlyList<(string Name,int Offset)> Firing(ExecutableRegion r){string[] n={"Punisher","Handgun","Red9","Blacktail","Broken Butterfly","Killer7","Shotgun","Striker","Rifle","Rifle semiautomático","TMP","Chicago Typewriter"};var v=T(r,0x34B7EC,0x34BA8C,0x31A88C,n,0x14).ToList();int d=r==ExecutableRegion.Slus?0:0x2A0;v.AddRange(new[]{("Mine Thrower",r==ExecutableRegion.DebugSlps?0x31A990:E(0x34B8F0+d)),("Handcannon",r==ExecutableRegion.DebugSlps?0x31A9A4:E(0x34B904+d)),("Riot Gun",r==ExecutableRegion.DebugSlps?0x31AB0C:E(0x34BA6C+d)),("Bowgun da Ada",r==ExecutableRegion.DebugSlps?0x31AC38:E(0x34BB98+d))});return v;}
public static IReadOnlyList<(string Name,int Offset)> Upgrades(ExecutableRegion r)=>T(r,0x335D78,0x335FF8,0x2ECBD8,new[]{"Handgun","Handgun com silenciador","Red9","Red9 com coronha","Matilda","Punisher","Punisher (medalhões)","Blacktail","Broken Butterfly","Shotgun","Striker","Riot Gun","Rifle","Rifle com mira","Rifle infravermelho","Rifle semiautomático","Semiautomático com mira","Semiautomático infravermelho","TMP","TMP com coronha","TMP do HUNK","Mine Thrower","Mine Thrower com mira","Chicago Typewriter","Killer7","Handcannon","Shotgun da Ada","Chicago da Ada","P.R.L. 412","Mira da P.R.L."},6);
public static IReadOnlyList<(string Name,int Offset)> Limits(ExecutableRegion r){int[] o=r switch{ExecutableRegion.Slus=>new[]{0x1EB94,0x1EBB0,0x1EBC4,0x1EBE0,0x1EBE4,0x1EC1C,0x1EC20,0x1EC3C,0x1EC7C,0x1EC80,0x1ECDC,0x1ED78},ExecutableRegion.Sles=>new[]{0x1ED04,0x1ED20,0x1ED34,0x1ED50,0x1ED54,0x1ED8C,0x1ED90,0x1EDAC,0x1EDEC,0x1EDF0,0x1EE4C,0x1EEE8},_=>new[]{0x20F54,0x20F70,0x20F84,0x20FA0,0x20FA4,0x20FDC,0x20FE0,0x20FFC,0x2103C,0x21040,0x2109C,0x21138}};string[] n={"Munição de handgun","Munição de magnum","Munição de Handcannon","Cartuchos","Cartuchos (Easy)","Munição de rifle","Munição de rifle (Easy)","TMP / Chicago","Minas (Easy)","Minas","Tesouros","Itens"};return n.Select((s,i)=>(s,o[i])).ToArray();}}
