using RE4_PS2_MOD_WORKSPACE.Core.Textures;
using RE4_PS2_MOD_WORKSPACE.Core.Visual;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed class AssetModelEditorForm : AppForm
{
    private readonly ScenarioViewport viewport = new() { Dock = DockStyle.Fill, BackColor = Color.FromArgb(13,15,18) };
    private readonly ListBox objects = new() { Dock = DockStyle.Fill, BackColor = Color.FromArgb(22,25,30), ForeColor = Color.Gainsboro, BorderStyle = BorderStyle.None };
    private readonly ListView resources = new() { Dock = DockStyle.Fill, View = View.Details, FullRowSelect = true, BackColor = Color.FromArgb(22,25,30), ForeColor = Color.Gainsboro, BorderStyle = BorderStyle.None };
    private readonly PictureBox texture = new() { Dock = DockStyle.Fill, SizeMode = PictureBoxSizeMode.Zoom, BackColor = Color.FromArgb(16,18,22) };
    private readonly ComboBox textureIndex = new() { Width=92,DropDownStyle=ComboBoxStyle.DropDownList,BackColor=Color.FromArgb(30,34,40),ForeColor=Color.White };
    private readonly Label status = new() { Dock = DockStyle.Bottom, Height = 30, Padding = new Padding(10,7,0,0), ForeColor = Color.FromArgb(155,162,174) };
    private readonly Label modelStats = new() { Dock = DockStyle.Bottom, Height = 76, Padding = new Padding(10,7,8,4), ForeColor = Color.FromArgb(180,186,197), BackColor = Color.FromArgb(28,31,37) };
    private readonly CheckBox keepConnected = new() { Text="Manter conectado", Checked=true, AutoSize=true, ForeColor=Color.Gainsboro, BackColor=Color.FromArgb(28,31,37), Margin=new Padding(12,5,4,0) };
    private readonly Dictionary<int,byte[]> edits = new();
    private EtmCatalog? catalog; private string? path; private bool dirty, isItm, standaloneBin;
    private byte[]? standaloneBinData, standaloneTplData;private string? workspaceRoot,configuredIso,activeAfsPath,embeddedDatPath,externalConverterPath;private readonly Action<IReadOnlyList<WeaponWorkspacePackage>>? weaponPackagesExtracted;private readonly Action<string>? externalConverterSelected;private readonly Dictionary<byte,WeaponDatPartSelection> embeddedWeaponParts=new();private int[] embeddedWeaponTpls=Array.Empty<int>();
    private sealed record ObjectItem(EtmObjectDefinition Definition,string Name){public override string ToString()=>Name;}
    private sealed class DarkToolStripColors:ProfessionalColorTable{public override Color ButtonSelectedGradientBegin=>Color.FromArgb(92,42,42);public override Color ButtonSelectedGradientEnd=>Color.FromArgb(92,42,42);public override Color ButtonPressedGradientBegin=>Color.FromArgb(126,48,48);public override Color ButtonPressedGradientEnd=>Color.FromArgb(126,48,48);public override Color ButtonCheckedGradientBegin=>Color.FromArgb(112,44,44);public override Color ButtonCheckedGradientEnd=>Color.FromArgb(112,44,44);public override Color ToolStripBorder=>Color.FromArgb(47,51,60);}

    public AssetModelEditorForm(string? workspaceRoot=null,string? configuredIso=null,string? activeAfsPath=null,Action<IReadOnlyList<WeaponWorkspacePackage>>? weaponPackagesExtracted=null,string? externalConverterPath=null,Action<string>? externalConverterSelected=null)
    {
        viewport.AssetMeshEditingEnabled=true;
        this.workspaceRoot=workspaceRoot;this.configuredIso=configuredIso;this.activeAfsPath=activeAfsPath;this.weaponPackagesExtracted=weaponPackagesExtracted;this.externalConverterPath=externalConverterPath;this.externalConverterSelected=externalConverterSelected;
        Text="Modelos de Objetos • RE4 PS2"; BackColor=Color.FromArgb(13,15,18); ForeColor=Color.Gainsboro; Font=new Font("Segoe UI",9); KeyPreview=true;
        StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(1420,860);MinimumSize=new Size(1100,700);
        resources.Columns.Add("Recurso",180); resources.Columns.Add("Tipo",70); resources.Columns.Add("Tamanho",90);
        objects.SelectedIndexChanged += (_,_) => SelectObject(); resources.SelectedIndexChanged += (_,_) => PreviewResource();
        viewport.AssetMeshSelectionChanged+=selection=>status.Text=selection==null?"Seleção limpa":selection.Value.Mode switch{AssetMeshSelectionMode.Vertex=>$"Vértice selecionado • parte {selection.Value.PartIndex+1} • tri {selection.Value.TriangleIndex+1}",AssetMeshSelectionMode.Edge=>$"Aresta selecionada • parte {selection.Value.PartIndex+1} • tri {selection.Value.TriangleIndex+1}",_=>$"Face selecionada • parte {selection.Value.PartIndex+1} • tri {selection.Value.TriangleIndex+1}"};
        viewport.AssetMeshTranslationRequested+=ApplyAssetTranslation;
        viewport.AssetMeshRotationRequested+=ApplyAssetRotation;
        var top=new FlowLayoutPanel{Dock=DockStyle.Top,Height=48,Padding=new Padding(8),WrapContents=false,BackColor=Color.FromArgb(22,25,30)};
        top.Controls.Add(B("ABRIR MODELO",(_,_)=>OpenPackage(),125));top.Controls.Add(B("ARMAS DAT",(_,_)=>OpenWeaponCatalog(),105));top.Controls.Add(B("IMPORTAR OBJ/SMD",async (_,_)=>await ImportExternalModelAsync(),145)); top.Controls.Add(B("CARREGAR TPL",(_,_)=>LoadStandaloneTpl(),115)); top.Controls.Add(B("SALVAR",(_,_)=>Save(false),86)); top.Controls.Add(B("SALVAR COMO",(_,_)=>Save(true),105)); top.Controls.Add(B("ENQUADRAR",(_,_)=>viewport.FitScene(),100));
        var tabs=new TabControl{Dock=DockStyle.Fill}; var modelTab=new TabPage("PARTES / RECURSOS"){BackColor=Color.FromArgb(22,25,30)}; modelTab.Controls.Add(resources);
        var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=76,Padding=new Padding(5),WrapContents=true,BackColor=Color.FromArgb(28,31,37)};
        actions.Controls.Add(B("EXPORTAR",(_,_)=>ExportSelected(),94)); actions.Controls.Add(B("SUBSTITUIR",(_,_)=>ReplaceSelected(),100)); actions.Controls.Add(B("RESTAUR",(_,_)=>RestoreSelected(),96));actions.Controls.Add(B("TESTAR TPL",(_,_)=>UseSelectedTpl(),96)); modelTab.Controls.Add(actions);
        var texTab=new TabPage("TEXTURA"){BackColor=Color.FromArgb(22,25,30)}; texTab.Controls.Add(texture); var texActions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=78,Padding=new Padding(4),WrapContents=true};texActions.Controls.Add(new Label{Text="Índice",AutoSize=true,ForeColor=Color.Silver,Margin=new Padding(5,9,2,0)});texActions.Controls.Add(textureIndex);texActions.Controls.Add(B("EXPORTAR PNG",(_,_)=>ExportPng(),110)); texActions.Controls.Add(B("TROCAR PNG",(_,_)=>ReplacePng(),105));texActions.Controls.Add(B("↻ 90°",(_,_)=>TransformSelectedTexture(RotateFlipType.Rotate90FlipNone,"rotacionada 90°",false),72));texActions.Controls.Add(B("INVERTER X",(_,_)=>TransformSelectedTexture(RotateFlipType.RotateNoneFlipX,"invertida em X",true),92));texActions.Controls.Add(B("INVERTER Y",(_,_)=>TransformSelectedTexture(RotateFlipType.RotateNoneFlipY,"invertida em Y",true),92)); texTab.Controls.Add(texActions); tabs.TabPages.Add(modelTab); tabs.TabPages.Add(texTab);textureIndex.SelectedIndexChanged+=(_,_)=>PreviewResource(false);
        var right=new SplitContainer{Dock=DockStyle.Fill,Orientation=Orientation.Horizontal,SplitterDistance=250}; right.Panel1.Controls.Add(objects);right.Panel1.Controls.Add(modelStats); right.Panel1.Controls.Add(new Label{Text="  OBJETOS DO PACOTE",Dock=DockStyle.Top,Height=28,ForeColor=Color.Silver,TextAlign=ContentAlignment.MiddleLeft}); right.Panel2.Controls.Add(tabs);
        var editTools=new ToolStrip{Dock=DockStyle.Top,GripStyle=ToolStripGripStyle.Hidden,BackColor=Color.FromArgb(28,31,37),ForeColor=Color.White,Padding=new Padding(6,4,4,4),Height=38,Renderer=new ToolStripProfessionalRenderer(new DarkToolStripColors())};
        editTools.Items.Add(new ToolStripLabel("SELEÇÃO  "));var modeButtons=new Dictionary<AssetMeshSelectionMode,ToolStripButton>();
        foreach(var pair in new[]{(AssetMeshSelectionMode.Object,"Objeto"),(AssetMeshSelectionMode.Vertex,"Vértice"),(AssetMeshSelectionMode.Edge,"Aresta"),(AssetMeshSelectionMode.Face,"Face")}){var button=new ToolStripButton(pair.Item2){CheckOnClick=true,Checked=pair.Item1==AssetMeshSelectionMode.Object,DisplayStyle=ToolStripItemDisplayStyle.Text,Margin=new Padding(2,0,2,0)};modeButtons[pair.Item1]=button;button.Click+=(_,_)=>{viewport.AssetSelectionMode=pair.Item1;foreach(var other in modeButtons)other.Value.Checked=other.Key==pair.Item1;status.Text=$"Modo de seleção: {pair.Item2}";};editTools.Items.Add(button);}
        editTools.Items.Add(new ToolStripSeparator());ToolStripButton moveTool=new("Mover"){Checked=true,CheckOnClick=true};ToolStripButton rotateTool=new("Rotacionar"){CheckOnClick=true};void SetTransform(AssetMeshTransformMode mode){viewport.AssetTransformMode=mode;moveTool.Checked=mode==AssetMeshTransformMode.Move;rotateTool.Checked=mode==AssetMeshTransformMode.Rotate;viewport.Invalidate();status.Text=mode==AssetMeshTransformMode.Move?"Gizmo de movimento":"Gizmo de rotação • arraste um eixo colorido";}moveTool.Click+=(_,_)=>SetTransform(AssetMeshTransformMode.Move);rotateTool.Click+=(_,_)=>SetTransform(AssetMeshTransformMode.Rotate);editTools.Items.Add(moveTool);editTools.Items.Add(rotateTool);
        editTools.Items.Add(new ToolStripSeparator());editTools.Items.Add(new ToolStripControlHost(keepConnected){ToolTipText="Move também os vértices duplicados na mesma posição, evitando abrir costuras da malha."});
        var main=new SplitContainer{Dock=DockStyle.Fill,FixedPanel=FixedPanel.Panel2}; main.Panel1.Controls.Add(viewport);main.Panel1.Controls.Add(editTools); main.Panel2.Controls.Add(right);
        Controls.Add(main); Controls.Add(status); Controls.Add(top); FormClosing+=OnClosing; KeyDown+=(_,e)=>{if(e.Control&&e.KeyCode==Keys.S){Save(false);e.SuppressKeyPress=true;}else if(e.KeyCode is Keys.D1 or Keys.NumPad1)SetTransform(AssetMeshTransformMode.Move);else if(e.KeyCode is Keys.D2 or Keys.NumPad2)SetTransform(AssetMeshTransformMode.Rotate);};
        Load+=(_,_)=>{main.Panel1MinSize=600;main.Panel2MinSize=390;main.SplitterDistance=Math.Max(main.Panel1MinSize,main.ClientSize.Width-430);};
        Shown+=(_,_)=>{SelectObject();viewport.Invalidate();};
    }
    private static Button B(string text,EventHandler click,int width){var b=new Button{Text=text,Width=width,Height=30,BackColor=Color.FromArgb(42,47,56),ForeColor=Color.White,FlatStyle=FlatStyle.Flat,Margin=new Padding(3)};b.FlatAppearance.BorderSize=0;b.Click+=click;return b;}
    private void OpenPackage(){using var d=new OpenFileDialog{Filter="Modelos e pacotes (*.bin;*.etm;*.itm)|*.bin;*.etm;*.itm|BIN avulso (*.bin)|*.bin|Pacotes (*.etm;*.itm)|*.etm;*.itm|Todos os arquivos|*.*"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;LoadPackage(d.FileName);}
    public void LoadPackage(string file){try{if(Path.GetExtension(file).Equals(".bin",StringComparison.OrdinalIgnoreCase)){LoadStandaloneBin(file);return;}isItm=Path.GetExtension(file).Equals(".itm",StringComparison.OrdinalIgnoreCase);standaloneBin=false;embeddedDatPath=null;embeddedWeaponParts.Clear();embeddedWeaponTpls=Array.Empty<int>();standaloneBinData=standaloneTplData=null;catalog=isItm?Ps2ItmReader.Read(file):Ps2EtmReader.Read(file);path=file;edits.Clear();dirty=false;objects.Items.Clear();foreach(var o in catalog.Objects.Values.OrderBy(x=>x.Id)){string name=isItm?ItaItemCatalog.GetName(o.Id):$"{EtsObjectNames.Get(o.Id)} (0x{o.Id:X2})";objects.Items.Add(new ObjectItem(o,name));}if(objects.Items.Count>0)objects.SelectedIndex=0;status.Text=$"{Path.GetFileName(file)} • {catalog.Objects.Count} {(isItm?"itens":"objetos")} • {catalog.Resources.Count} recursos";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Não foi possível abrir",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private void LoadStandaloneBin(string file){embeddedDatPath=null;embeddedWeaponParts.Clear();embeddedWeaponTpls=Array.Empty<int>();LoadStandaloneData(File.ReadAllBytes(file),null,file,Path.GetFileNameWithoutExtension(file)+" • BIN avulso");}
    private void LoadStandaloneData(byte[] bin,byte[]? tpl,string source,string label){var triangles=Ps2ScenarioReader.ReadStandaloneBin(bin);var br=new EtmResource(0,2,label+".bin",bin);EtmResource? tr=tpl==null?null:new EtmResource(100000,3,label+".tpl",tpl);var rr=tr==null?new[]{br}:new[]{br,tr};standaloneBin=true;isItm=false;standaloneBinData=bin;standaloneTplData=tpl;path=source;edits.Clear();dirty=false;var definition=new EtmObjectDefinition(0,rr);catalog=new EtmCatalog{SourcePath=source,Resources=rr,Objects=new Dictionary<byte,EtmObjectDefinition>{{0,definition}},Models=new Dictionary<byte,IReadOnlyList<ScenarioTriangle>>{{0,triangles}},ModelParts=new Dictionary<byte,IReadOnlyList<EtmModelPart>>{{0,new[]{new EtmModelPart(br,null,tr,triangles)}}}};objects.Items.Clear();objects.Items.Add(new ObjectItem(definition,label));objects.SelectedIndex=0;status.Text=$"{label} • {triangles.Count:N0} triângulos";}
    private void OpenWeaponCatalog(){using var browser=new WeaponDatBrowserForm(workspaceRoot,configuredIso,activeAfsPath,weaponPackagesExtracted);if(browser.ShowLocalizedDialog(this)!=DialogResult.OK||browser.Selection is not WeaponDatSelection selected)return;LoadWeaponDatPackage(selected.DatPath,selected.Parts);}
    private void LoadWeaponDatPackage(string datPath,IReadOnlyList<WeaponDatPartSelection> parts){try{embeddedDatPath=datPath;embeddedWeaponParts.Clear();for(int i=0;i<parts.Count&&i<256;i++)embeddedWeaponParts[(byte)i]=parts[i];var archive=Core.Dat.NativeDatService.Read(datPath);embeddedWeaponTpls=archive.Entries.Where(x=>x.Type.Equals("TPL",StringComparison.OrdinalIgnoreCase)).Select(x=>x.Index).ToArray();standaloneBin=false;standaloneBinData=standaloneTplData=null;isItm=false;path=datPath;edits.Clear();dirty=false;catalog=BuildWeaponCatalog();objects.Items.Clear();foreach(var pair in catalog.Objects.OrderBy(x=>x.Key)){var part=embeddedWeaponParts[pair.Key];objects.Items.Add(new ObjectItem(pair.Value,$"BIN #{part.BinEntry:D3}"+(part.TplEntry>=0?$"  •  TPL #{part.TplEntry:D3}":"  •  sem textura")));}if(objects.Items.Count>0)objects.SelectedIndex=0;status.Text=$"{WeaponNameCatalog.Display(datPath)} • {parts.Count} modelo(s) • {embeddedWeaponTpls.Length} TPL(s)";}catch(Exception ex){embeddedDatPath=null;MessageBox.Show(this,ex.Message,"Não foi possível abrir a arma",MessageBoxButtons.OK,MessageBoxIcon.Error);}}
    private EtmCatalog BuildWeaponCatalog(){if(embeddedDatPath==null)return new();var archive=Core.Dat.NativeDatService.Read(embeddedDatPath);var resources=archive.Entries.Where(x=>x.Type.Equals("BIN",StringComparison.OrdinalIgnoreCase)||x.Type.Equals("TPL",StringComparison.OrdinalIgnoreCase)).ToDictionary(x=>x.Index,x=>new EtmResource(x.Index,x.Type.Equals("BIN",StringComparison.OrdinalIgnoreCase)?2:3,$"{Path.GetFileNameWithoutExtension(embeddedDatPath)}_{x.Index:D3}.{x.Type.ToLowerInvariant()}",edits.TryGetValue(x.Index,out var changed)?changed:x.Data));var objectsById=new Dictionary<byte,EtmObjectDefinition>();var models=new Dictionary<byte,IReadOnlyList<ScenarioTriangle>>();var modelParts=new Dictionary<byte,IReadOnlyList<EtmModelPart>>();foreach(var pair in embeddedWeaponParts){EtmResource bin=resources[pair.Value.BinEntry];EtmResource? active=pair.Value.TplEntry>=0&&resources.TryGetValue(pair.Value.TplEntry,out var t)?t:null;ScenarioTriangle[] triangles=Ps2ScenarioReader.ReadStandaloneBin(bin.Data).ToArray();EtmResource[] visible=new[]{bin}.Concat(embeddedWeaponTpls.Where(resources.ContainsKey).Select(x=>resources[x])).ToArray();objectsById[pair.Key]=new EtmObjectDefinition(pair.Key,visible);models[pair.Key]=triangles;modelParts[pair.Key]=new[]{new EtmModelPart(bin,null,active,triangles)};}return new EtmCatalog{SourcePath=embeddedDatPath,Resources=resources.Values.ToArray(),Objects=objectsById,Models=models,ModelParts=modelParts};}
    private void UseSelectedTpl(){if(embeddedDatPath==null||Selected() is not EtmResource tpl||!tpl.Name.EndsWith(".tpl",StringComparison.OrdinalIgnoreCase)||objects.SelectedItem is not ObjectItem item)return;embeddedWeaponParts[item.Definition.Id]=embeddedWeaponParts[item.Definition.Id] with{TplEntry=tpl.FileOrder};catalog=BuildWeaponCatalog();SelectObject(true);status.Text=$"BIN #{embeddedWeaponParts[item.Definition.Id].BinEntry:D3} testando TPL #{tpl.FileOrder:D3} • associação apenas visual";}
    private void SelectObject(bool preserveView=false){viewport.SetAssetMeshSelection(null);if(catalog==null||objects.SelectedItem is not ObjectItem item)return;EtmCatalog effective=EffectiveCatalog();EtmObjectDefinition o=effective.Objects.TryGetValue(item.Definition.Id,out var current)?current:item.Definition;resources.Items.Clear();foreach(var r in o.Resources){var row=new ListViewItem(r.Name){Tag=r};row.SubItems.Add(r.Name.EndsWith(".bin",StringComparison.OrdinalIgnoreCase)?"Modelo":r.Name.EndsWith(".tpl",StringComparison.OrdinalIgnoreCase)?"Textura":$"0x{r.Type:X}");row.SubItems.Add(FormatSize(edits.TryGetValue(r.FileOrder,out var v)?v.Length:r.Data.Length));resources.Items.Add(row);}UpdateStats(effective,o.Id);ShowPreview(effective,o.Id,preserveView);}
    private void UpdateStats(EtmCatalog source,byte id){if(!source.ModelParts.TryGetValue(id,out var parts)){modelStats.Text="SEM GEOMETRIA";return;}var tris=parts.SelectMany(p=>p.Triangles).ToArray();int vertices=0,edges=0,materials=0;foreach(var part in parts){var doc=Ps2BinDocument.Parse(Data(part.Bin));vertices+=doc.Vertices.Count;edges+=doc.Edges.Count;materials+=doc.Materials.Count;}var points=tris.SelectMany(t=>new[]{t.A,t.B,t.C}).ToArray();var min=points.Aggregate(new System.Numerics.Vector3(float.PositiveInfinity),System.Numerics.Vector3.Min);var max=points.Aggregate(new System.Numerics.Vector3(float.NegativeInfinity),System.Numerics.Vector3.Max);var size=max-min;modelStats.Text=$"MALHA  •  {tris.Length:N0} faces  •  {vertices:N0} vértices  •  {edges:N0} arestas\n{parts.Count} parte(s)  •  {materials} material(is)  •  {size.X:0.##} × {size.Y:0.##} × {size.Z:0.##}";}
    private void ApplyAssetTranslation(AssetMeshSelection selection,System.Numerics.Vector3 worldDelta){TransformAssetSelection(selection,worldDelta,false);}
    private void ApplyAssetRotation(AssetMeshSelection selection,System.Numerics.Vector3 rotationDegrees){TransformAssetSelection(selection,rotationDegrees,true);}
    private void TransformAssetSelection(AssetMeshSelection selection,System.Numerics.Vector3 value,bool rotate){if(objects.SelectedItem is not ObjectItem item)return;EtmCatalog effective=EffectiveCatalog();if(!effective.ModelParts.TryGetValue(item.Definition.Id,out var parts)||selection.PartIndex<0||selection.PartIndex>=parts.Count)return;EtmModelPart part=parts[selection.PartIndex];if(selection.TriangleIndex<0||selection.TriangleIndex>=part.Triangles.Count)return;ScenarioTriangle tri=part.Triangles[selection.TriangleIndex];int[] offsets=selection.Mode switch{AssetMeshSelectionMode.Vertex=>new[]{selection.ElementIndex==0?tri.SourceOffsetA:selection.ElementIndex==1?tri.SourceOffsetB:tri.SourceOffsetC},AssetMeshSelectionMode.Edge=>selection.ElementIndex switch{0=>new[]{tri.SourceOffsetA,tri.SourceOffsetB},1=>new[]{tri.SourceOffsetB,tri.SourceOffsetC},_=>new[]{tri.SourceOffsetC,tri.SourceOffsetA}},_=>new[]{tri.SourceOffsetA,tri.SourceOffsetB,tri.SourceOffsetC}};try{var document=Ps2BinDocument.Parse(Data(part.Bin));if(selection.Mode==AssetMeshSelectionMode.Object)offsets=document.Vertices.Select(v=>v.Offset).ToArray();else if(keepConnected.Checked){var selectedPositions=document.Vertices.Where(v=>offsets.Contains(v.Offset)).Select(v=>v.Position).ToArray();const float seamTolerance=.00001f;offsets=document.Vertices.Where(v=>selectedPositions.Any(p=>System.Numerics.Vector3.DistanceSquared(p,v.Position)<=seamTolerance)).Select(v=>v.Offset).ToArray();}if(rotate)document.Rotate(offsets,value);else document.Translate(offsets,value/(isItm?.01f:1f));edits[part.Bin.FileOrder]=document.Source;Changed($"{selection.Mode} {(rotate?"rotacionado":"movido")}{(keepConnected.Checked&&selection.Mode!=AssetMeshSelectionMode.Object?" • conexões preservadas":"")}");SelectObject(true);}catch(Exception ex){MessageBox.Show(this,ex.Message,"Não foi possível editar a malha",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
    private void ShowPreview(EtmCatalog effective,byte id,bool preserveView=false){if(!effective.Models.TryGetValue(id,out var mesh)||mesh.Count==0)return;float scale=isItm?.01f:1f;var points=mesh.SelectMany(t=>new[]{t.A,t.B,t.C}).Select(p=>p*scale).ToArray();var min=points.Aggregate(new System.Numerics.Vector3(float.PositiveInfinity),System.Numerics.Vector3.Min);var max=points.Aggregate(new System.Numerics.Vector3(float.NegativeInfinity),System.Numerics.Vector3.Max);float pad=Math.Max(0.1f,(max-min).Length()*.08f);viewport.SetScene(new ScenarioScene{BoundsMin=min-new System.Numerics.Vector3(pad),BoundsMax=max+new System.Numerics.Vector3(pad),Triangles=new()},!preserveView);if(isItm){var scene=new ItaScene();scene.Entries.Add(new ItaEntry{ItemId=id,FileOrder=0,AppearanceType=0});viewport.SetEtsScene(null,null);viewport.SetItaScene(scene,effective);viewport.SelectItaEntry(scene.Entries[0]);}else{var scene=new EtsScene();scene.Entries.Add(new EtsEntry{ObjectId=id,InstanceIndex=0,ScaleX=1,ScaleY=1,ScaleZ=1});viewport.SetItaScene(null,null);viewport.SetEtsScene(scene,effective);viewport.SelectEtsEntry(scene.Entries[0]);}viewport.Invalidate();}
    private EtmCatalog EffectiveCatalog(){if(catalog==null||path==null)return new();if(embeddedDatPath!=null)return BuildWeaponCatalog();if(standaloneBin){byte[] bin=edits.TryGetValue(0,out var edited)?edited:standaloneBinData!;var triangles=Ps2ScenarioReader.ReadStandaloneBin(bin);var br=new EtmResource(0,2,Path.GetFileName(path),bin);byte[]? tplBytes=edits.TryGetValue(100000,out var editedTpl)?editedTpl:standaloneTplData;EtmResource? tpl=tplBytes==null?null:new EtmResource(100000,3,Path.GetFileNameWithoutExtension(path)+".tpl",tplBytes);var all=tpl==null?new[]{br}:new[]{br,tpl};var definition=new EtmObjectDefinition(0,all);return new EtmCatalog{SourcePath=path,Resources=all,Objects=new Dictionary<byte,EtmObjectDefinition>{{0,definition}},Models=new Dictionary<byte,IReadOnlyList<ScenarioTriangle>>{{0,triangles}},ModelParts=new Dictionary<byte,IReadOnlyList<EtmModelPart>>{{0,new[]{new EtmModelPart(br,null,tpl,triangles)}}}};}var temp=Path.Combine(Path.GetTempPath(),"asset_preview_"+Guid.NewGuid().ToString("N")+Path.GetExtension(path));Ps2AssetPackageEditor.Save(path,temp,edits);try{return Path.GetExtension(path).Equals(".itm",StringComparison.OrdinalIgnoreCase)?Ps2ItmReader.Read(temp):Ps2EtmReader.Read(temp);}finally{try{File.Delete(temp);}catch{}}}
    private void LoadStandaloneTpl(){if(!standaloneBin){MessageBox.Show(this,"O carregamento separado de TPL é usado quando um BIN avulso está aberto.","Carregar textura",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}using var d=new OpenFileDialog{Filter="Pacote de texturas TPL (*.tpl)|*.tpl|Todos os arquivos|*.*"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;try{byte[] candidate=File.ReadAllBytes(d.FileName);using(var ms=new MemoryStream(candidate))using(var br=new BinaryReader(ms))new TplReader().ReadTexture(br,0);standaloneTplData=candidate;catalog=EffectiveCatalog();objects.Items.Clear();objects.Items.Add(new ObjectItem(catalog.Objects[0],Path.GetFileNameWithoutExtension(path)+" • BIN + TPL"));objects.SelectedIndex=0;status.Text=$"{Path.GetFileName(path)} • textura {Path.GetFileName(d.FileName)} carregada";}catch(Exception ex){MessageBox.Show(this,ex.Message,"TPL inválido",MessageBoxButtons.OK,MessageBoxIcon.Warning);}}
    private EtmResource? Selected()=>resources.SelectedItems.Count==0?null:resources.SelectedItems[0].Tag as EtmResource;
    private byte[] Data(EtmResource r)=>edits.TryGetValue(r.FileOrder,out var d)?d:r.Data;
    private int CurrentTextureIndex=>textureIndex.SelectedItem is TextureIndexItem item?item.Index:0;
    private void PreviewResource()=>PreviewResource(true);
    private void PreviewResource(bool rebuildIndices){var r=Selected();texture.Image?.Dispose();texture.Image=null;if(rebuildIndices)textureIndex.Items.Clear();if(r==null||!r.Name.EndsWith(".tpl",StringComparison.OrdinalIgnoreCase))return;string temp=Path.Combine(Path.GetTempPath(),"asset_tpl_preview_"+Guid.NewGuid().ToString("N")+".tpl");try{File.WriteAllBytes(temp,Data(r));var service=new TextureWorkspaceService();if(rebuildIndices){foreach(var info in service.ReadCatalog(temp))textureIndex.Items.Add(new TextureIndexItem(info.Index,$"#{info.Index:D2} • {info.Width}×{info.Height}"));if(textureIndex.Items.Count>0)textureIndex.SelectedIndex=0;return;}texture.Image=service.Decode(temp,CurrentTextureIndex);}catch{}finally{try{File.Delete(temp);}catch{}}}
    private sealed record TextureIndexItem(int Index,string Label){public override string ToString()=>Label;}
    private void ExportSelected(){var r=Selected();if(r==null)return;using var d=new SaveFileDialog{FileName=r.Name,Filter="Todos os arquivos|*.*"};if(d.ShowLocalizedDialog(this)==DialogResult.OK)File.WriteAllBytes(d.FileName,Data(r));}
    private void ReplaceSelected(){var r=Selected();if(r==null)return;using var d=new OpenFileDialog{Filter=r.Name.EndsWith(".bin",StringComparison.OrdinalIgnoreCase)?"Modelo BIN do PS2 (*.bin)|*.bin|Todos os arquivos|*.*":"Arquivo compatível|*.*"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;byte[] candidate=File.ReadAllBytes(d.FileName);if(r.Name.EndsWith(".bin",StringComparison.OrdinalIgnoreCase)){try{Ps2ScenarioReader.ReadStandaloneBin(candidate);}catch(Exception ex){MessageBox.Show(this,"Esse BIN não contém uma malha PS2 compatível.\n\n"+ex.Message,"Modelo inválido",MessageBoxButtons.OK,MessageBoxIcon.Warning);return;}}edits[r.FileOrder]=candidate;Changed($"{r.Name} substituído");SelectObject();}
    private async Task ImportExternalModelAsync()
    {
        if(catalog==null||objects.SelectedItem is not ObjectItem selectedObject){MessageBox.Show(this,"Abra um modelo e selecione o objeto que receberá a nova malha.","Importar modelo",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}EtmCatalog effective=EffectiveCatalog();if(!effective.ModelParts.TryGetValue(selectedObject.Definition.Id,out var parts)||parts.Count==0){MessageBox.Show(this,"O objeto selecionado não possui um BIN receptor.","Importar modelo",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}EtmModelPart receiver=parts[0];using var file=new OpenFileDialog{Title="Escolha o modelo externo",Filter="Modelos compatíveis (*.obj;*.smd)|*.obj;*.smd|Wavefront OBJ (*.obj)|*.obj|StudioModelData com ossos (*.smd)|*.smd"};if(file.ShowLocalizedDialog(this)!=DialogResult.OK)return;
        try
        {
            ExternalModelStats stats=ExternalPs2ModelConverter.Analyze(file.FileName);byte[] template=Data(receiver.Bin);bool hasBones=false;try{hasBones=Core.Animation.Ps2BinSkeletonReader.Read(template,"receiver").Bones.Count>0;}catch{}using var wizard=new ExternalModelImportDialog(file.FileName,stats,hasBones,receiver.Triangles);if(wizard.ShowLocalizedDialog(this)!=DialogResult.OK)return;string? converter=ResolveExternalConverterPath();if(converter==null)return;UseWaitCursor=true;status.Text=$"Convertendo {Path.GetFileName(file.FileName)} para o formato BIN do PS2...";string generated=await ExternalPs2ModelConverter.ConvertAsync(converter,file.FileName,template,wizard.AutoWeight,default,wizard.Options);try{byte[] converted=File.ReadAllBytes(generated);var parsed=Ps2BinDocument.Parse(converted);if(parsed.Faces.Count==0)throw new InvalidDataException("O BIN convertido não contém faces renderizáveis.");edits[receiver.Bin.FileOrder]=converted;if(wizard.ImportCompanionTexture&&receiver.TextureFallback!=null){string png=Path.ChangeExtension(file.FileName,".png"),temp=Path.Combine(Path.GetTempPath(),"asset_import_tpl_"+Guid.NewGuid().ToString("N")+".tpl");try{File.WriteAllBytes(temp,Data(receiver.TextureFallback));int textureIndex=receiver.Triangles.Select(x=>x.TextureIndex).DefaultIfEmpty(0).First();new TextureWorkspaceService().ReplaceFromImage(temp,textureIndex,png);edits[receiver.TextureFallback.FileOrder]=File.ReadAllBytes(temp);}finally{try{File.Delete(temp);}catch{}}}Changed($"{Path.GetFileName(file.FileName)} importado • {stats.Vertices:N0} vértices • {stats.Faces:N0} faces");SelectObject(false);}finally{try{File.Delete(generated);}catch{}}
        }
        catch(Exception ex){MessageBox.Show(this,ex.Message,"Não foi possível importar o modelo",MessageBoxButtons.OK,MessageBoxIcon.Error);}
        finally{UseWaitCursor=false;}
    }
    private string? ResolveExternalConverterPath(){if(!string.IsNullOrWhiteSpace(externalConverterPath)&&File.Exists(externalConverterPath))return externalConverterPath;foreach(string folder in new[]{Application.StartupPath,Path.Combine(Application.StartupPath,"Tools")})foreach(string name in new[]{"RE4_PS2_BIN_TOOL.exe","Re4Ps2BINrepack.exe"}){string candidate=Path.Combine(folder,name);if(File.Exists(candidate))return externalConverterPath=candidate;}using var dialog=new OpenFileDialog{Title="Selecione a RE4 PS2 BIN Tool",Filter="RE4 PS2 BIN Tool (*.exe)|*.exe"};if(dialog.ShowLocalizedDialog(this)!=DialogResult.OK)return null;externalConverterPath=dialog.FileName;externalConverterSelected?.Invoke(dialog.FileName);return externalConverterPath;}
    private void RestoreSelected(){var r=Selected();if(r==null)return;edits.Remove(r.FileOrder);dirty=edits.Count>0;status.Text=dirty?$"{r.Name} restaurado • alterações pendentes":$"{r.Name} restaurado • pacote sem alterações";SelectObject();}
    private void ExportPng(){var r=Selected();if(r==null||texture.Image==null)return;using var d=new SaveFileDialog{FileName=Path.GetFileNameWithoutExtension(r.Name)+$"_{CurrentTextureIndex:D2}.png",Filter="PNG|*.png"};if(d.ShowLocalizedDialog(this)==DialogResult.OK)texture.Image.Save(d.FileName,System.Drawing.Imaging.ImageFormat.Png);}
    private void ReplacePng(){var r=Selected();if(r==null||!r.Name.EndsWith(".tpl",StringComparison.OrdinalIgnoreCase))return;using var d=new OpenFileDialog{Filter="Imagem PNG|*.png"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;string temp=Path.Combine(Path.GetTempPath(),"asset_tpl_"+Guid.NewGuid().ToString("N")+".tpl");try{File.WriteAllBytes(temp,Data(r));new TextureWorkspaceService().ReplaceFromImage(temp,CurrentTextureIndex,d.FileName);edits[r.FileOrder]=File.ReadAllBytes(temp);Changed($"Textura #{CurrentTextureIndex} substituída");SelectObject();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Falha na textura");}finally{try{File.Delete(temp);}catch{}}}
    private void TransformSelectedTexture(RotateFlipType transform,string description,bool preserveDimensions){var r=Selected();if(r==null||!r.Name.EndsWith(".tpl",StringComparison.OrdinalIgnoreCase))return;int index=CurrentTextureIndex;string temp=Path.Combine(Path.GetTempPath(),"asset_tpl_transform_"+Guid.NewGuid().ToString("N")+".tpl");try{File.WriteAllBytes(temp,Data(r));var service=new TextureWorkspaceService();using Bitmap bitmap=service.Decode(temp,index);bitmap.RotateFlip(transform);service.ReplaceFromBitmap(temp,index,bitmap,preserveDimensions);edits[r.FileOrder]=File.ReadAllBytes(temp);Changed($"Textura #{index} {description}");SelectObject(true);for(int i=0;i<resources.Items.Count;i++)if(resources.Items[i].Tag is EtmResource item&&item.FileOrder==r.FileOrder){resources.Items[i].Selected=true;resources.Select();break;}textureIndex.SelectedIndex=Math.Min(index,textureIndex.Items.Count-1);viewport.Invalidate();}catch(Exception ex){MessageBox.Show(this,ex.Message,"Não foi possível transformar a textura",MessageBoxButtons.OK,MessageBoxIcon.Warning);}finally{try{File.Delete(temp);}catch{}}}
    private void Save(bool choose){if(path==null)return;string destination=path;if(choose){using var d=new SaveFileDialog{FileName=Path.GetFileName(path),Filter=embeddedDatPath!=null?"Pacote de arma DAT (*.dat)|*.dat":standaloneBin?"Modelo BIN (*.bin)|*.bin|Todos os arquivos|*.*":"Pacote de objetos|*.etm;*.itm|Todos os arquivos|*.*"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;destination=d.FileName;}try{if(embeddedDatPath!=null){string source=embeddedDatPath;if(choose&&!Path.GetFullPath(source).Equals(Path.GetFullPath(destination),StringComparison.OrdinalIgnoreCase))File.Copy(source,destination,true);if(!File.Exists(destination+".bak"))File.Copy(destination,destination+".bak");foreach(var edit in edits)Ps2CharacterDatEditor.RestoreDatEntry(destination,edit.Key,edit.Value);SyncWeaponContentEntries(destination,edits);WeaponDatPartSelection[] mappings=embeddedWeaponParts.OrderBy(x=>x.Key).Select(x=>x.Value).ToArray();LoadWeaponDatPackage(destination,mappings);}else{if(!choose&&!File.Exists(path+".bak"))File.Copy(path,path+".bak");if(standaloneBin)File.WriteAllBytes(destination,edits.TryGetValue(0,out var bin)?bin:standaloneBinData!);else Ps2AssetPackageEditor.Save(path,destination,edits);LoadPackage(destination);}status.Text="Salvo com sucesso • backup preservado";}catch(Exception ex){MessageBox.Show(this,ex.Message,"Falha ao salvar");}}
    private static void SyncWeaponContentEntries(string datPath,IReadOnlyDictionary<int,byte[]> changed){if(changed.Count==0)return;string? directory=Path.GetDirectoryName(datPath);if(directory==null||!Directory.Exists(directory)||!Directory.EnumerateFiles(directory,"*.idx",SearchOption.TopDirectoryOnly).Any())return;string name=Path.GetFileNameWithoutExtension(datPath);foreach(var edit in changed){string marker=$"_{edit.Key:D2}.";string marker3=$"_{edit.Key:D3}.";string? entry=Directory.EnumerateFiles(directory,name+"_*.*",SearchOption.AllDirectories).FirstOrDefault(x=>Path.GetFileName(x).Contains(marker,StringComparison.OrdinalIgnoreCase)||Path.GetFileName(x).Contains(marker3,StringComparison.OrdinalIgnoreCase));if(entry!=null)File.WriteAllBytes(entry,edit.Value);}}
    private void Changed(string message){dirty=true;status.Text=message+" • alterações pendentes";}
    private void OnClosing(object? s,FormClosingEventArgs e){if(dirty&&MessageBox.Show(this,"Há alterações não salvas. Deseja fechar mesmo assim?","Modelos de Objetos",MessageBoxButtons.YesNo,MessageBoxIcon.Warning)!=DialogResult.Yes)e.Cancel=true;}
    private static string FormatSize(long b)=>b<1024?$"{b} B":b<1048576?$"{b/1024d:0.0} KB":$"{b/1048576d:0.0} MB";
}
