using System.Text.RegularExpressions;
using RE4_PS2_MOD_WORKSPACE.Core.Afs;
using RE4_PS2_MOD_WORKSPACE.Core.Dat;
using RE4_PS2_MOD_WORKSPACE.Core.Visual;

namespace RE4_PS2_MOD_WORKSPACE;

public sealed record WeaponDatPartSelection(int BinEntry,int TplEntry);
public sealed record WeaponDatSelection(string DatPath,IReadOnlyList<WeaponDatPartSelection> Parts);
public sealed record WeaponWorkspacePackage(string DatName,string OriginalDatPath,string ContentPath);

public sealed class WeaponDatBrowserForm : AppForm
{
    private static readonly Regex WeaponName=new("^wep[0-9a-f]{2}\\.dat$",RegexOptions.IgnoreCase|RegexOptions.Compiled);
    private readonly string? workspaceRoot,configuredIso,activeAfsPath;private readonly Action<IReadOnlyList<WeaponWorkspacePackage>>? packagesExtracted;private readonly ComboBox packages=new(){Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};
    private readonly ListView models=new(){Dock=DockStyle.Fill,View=View.Details,FullRowSelect=true,MultiSelect=true,HideSelection=false,BackColor=Color.FromArgb(22,25,30),ForeColor=Color.Gainsboro,BorderStyle=BorderStyle.None};private readonly ComboBox testTpl=new(){Width=190,DropDownStyle=ComboBoxStyle.DropDownList};
    private readonly Label summary=new(){Dock=DockStyle.Bottom,Height=30,Padding=new Padding(10,7,0,0),ForeColor=Color.FromArgb(160,168,180)};
    public WeaponDatSelection? Selection{get;private set;}
    private sealed record DatItem(string Path){public override string ToString()=>WeaponNameCatalog.Display(Path)+"  •  "+System.IO.Path.GetDirectoryName(Path);}
    private sealed class ModelItem{public int Bin,Tpl,Faces;public long Size;public ModelItem(int bin,int tpl,int faces,long size){Bin=bin;Tpl=tpl;Faces=faces;Size=size;}public override string ToString()=>$"Modelo BIN #{Bin:D3}";}
    private sealed record TplItem(int Entry){public override string ToString()=>Entry<0?"Sem textura":$"TPL #{Entry:D3}";}

    public WeaponDatBrowserForm(string? workspaceRoot,string? configuredIso=null,string? activeAfsPath=null,Action<IReadOnlyList<WeaponWorkspacePackage>>? packagesExtracted=null)
    {
        this.workspaceRoot=workspaceRoot;this.configuredIso=configuredIso;this.activeAfsPath=activeAfsPath;this.packagesExtracted=packagesExtracted;Text="Armas • wepXX.dat";StartPosition=FormStartPosition.CenterParent;ClientSize=new Size(900,620);MinimumSize=new Size(720,480);BackColor=Color.FromArgb(13,15,18);ForeColor=Color.Gainsboro;Font=new Font("Segoe UI",9);
        models.Columns.Add("Modelo",190);models.Columns.Add("Texturas",170);models.Columns.Add("Faces",100);models.Columns.Add("Tamanho",110);models.Columns.Add("Entrada DAT",120);
        var header=new TableLayoutPanel{Dock=DockStyle.Top,Height=76,ColumnCount=4,Padding=new Padding(10,10,10,8),BackColor=Color.FromArgb(28,31,37)};header.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,100));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,115));header.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,145));header.Controls.Add(packages,0,0);header.Controls.Add(Button("ATUALIZAR",(_,_)=>Discover(),92),1,0);header.Controls.Add(Button("OUTRO DAT",(_,_)=>Browse(),105),2,0);header.Controls.Add(Button("EXTRAIR DO AFS",async (_,_)=>await ExtractFromAfsAsync(),135),3,0);
        var tplBar=new FlowLayoutPanel{Dock=DockStyle.Top,Height=42,Padding=new Padding(10,5,5,4),BackColor=Color.FromArgb(22,25,30)};tplBar.Controls.Add(new Label{Text="TPL usado para testar os BIN selecionados:",AutoSize=true,Margin=new Padding(0,7,8,0),ForeColor=Color.Silver});tplBar.Controls.Add(testTpl);
        var actions=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=52,Padding=new Padding(8),FlowDirection=FlowDirection.RightToLeft,BackColor=Color.FromArgb(28,31,37)};actions.Controls.Add(Button("ABRIR PACOTE TODO",(_,_)=>OpenModels(true),155));actions.Controls.Add(Button("ABRIR SELECIONADOS",(_,_)=>OpenModels(false),170));actions.Controls.Add(Button("EXTRAIR TUDO",(_,_)=>Extract(true),120));actions.Controls.Add(Button("EXTRAIR SELEÇÃO",(_,_)=>Extract(false),140));
        Controls.Add(models);Controls.Add(tplBar);Controls.Add(summary);Controls.Add(actions);Controls.Add(header);packages.SelectedIndexChanged+=(_,_)=>LoadPackage();models.SelectedIndexChanged+=(_,_)=>SyncTplChoice();testTpl.SelectedIndexChanged+=(_,_)=>ApplyTplChoice();models.DoubleClick+=(_,_)=>OpenModels(false);Shown+=(_,_)=>{MigrateLegacyWeapons();Discover();};
    }
    private static Button Button(string text,EventHandler click,int width){var b=new Button{Text=text,Width=width,Height=30,FlatStyle=FlatStyle.Flat,BackColor=Color.FromArgb(45,50,60),ForeColor=Color.White,Margin=new Padding(4)};b.FlatAppearance.BorderSize=0;b.Click+=click;return b;}
    private void Discover(string? preferred=null)
    {
        var found=new HashSet<string>(StringComparer.OrdinalIgnoreCase);foreach(string root in new[]{workspaceRoot,Application.StartupPath}.Where(x=>!string.IsNullOrWhiteSpace(x)&&Directory.Exists(x))!)try{foreach(string file in Directory.EnumerateFiles(root!,"wep??.dat",SearchOption.AllDirectories))if(WeaponName.IsMatch(Path.GetFileName(file))&&!IsBackup(file))found.Add(Path.GetFullPath(file));}catch{}
        packages.Items.Clear();foreach(string file in found.OrderBy(Path.GetFileName,StringComparer.OrdinalIgnoreCase).ThenBy(x=>x,StringComparer.OrdinalIgnoreCase))packages.Items.Add(new DatItem(file));
        int selected=-1;for(int i=0;i<packages.Items.Count;i++)if(packages.Items[i] is DatItem d&&string.Equals(d.Path,preferred,StringComparison.OrdinalIgnoreCase)){selected=i;break;}packages.SelectedIndex=selected>=0?selected:(packages.Items.Count>0?0:-1);if(packages.Items.Count==0)summary.Text="Nenhum wepXX.dat encontrado no workspace. Use OUTRO DAT para localizar um arquivo.";
    }
    private static bool IsBackup(string path)=>path.EndsWith(".bak",StringComparison.OrdinalIgnoreCase)||path.Contains($"{Path.DirectorySeparatorChar}OriginalDAT{Path.DirectorySeparatorChar}",StringComparison.OrdinalIgnoreCase)||path.Contains($"{Path.DirectorySeparatorChar}Extracted{Path.DirectorySeparatorChar}Weapons{Path.DirectorySeparatorChar}",StringComparison.OrdinalIgnoreCase);
    private void Browse(){using var d=new OpenFileDialog{Title="Abrir pacote de arma",Filter="Pacote de arma (wepXX.dat)|wep??.dat|DAT (*.dat)|*.dat"};if(d.ShowLocalizedDialog(this)!=DialogResult.OK)return;if(!WeaponName.IsMatch(Path.GetFileName(d.FileName))){MessageBox.Show(this,"Escolha um arquivo no padrão wepXX.dat.","Pacote de arma",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}Discover(Path.GetFullPath(d.FileName));}
    private async Task ExtractFromAfsAsync()
    {
        string? iso=configuredIso;if(string.IsNullOrWhiteSpace(iso)||!File.Exists(iso)){using var pick=new OpenFileDialog{Title="Selecione a ISO de Resident Evil 4",Filter="Imagem de disco (*.iso)|*.iso|Todos os arquivos|*.*"};if(pick.ShowLocalizedDialog(this)!=DialogResult.OK)return;iso=pick.FileName;}
        try
        {
            summary.Text="Lendo a ISO e procurando armas no AFS...";UseWaitCursor=true;
            var result=await Task.Run(()=>{var afsFiles=AfsService.FindAfsFiles(iso!);var afsFile=afsFiles.FirstOrDefault(x=>!string.IsNullOrWhiteSpace(activeAfsPath)&&x.FullPath.Equals(activeAfsPath,StringComparison.OrdinalIgnoreCase))??afsFiles.FirstOrDefault(x=>x.Name.Equals("BIO4DAT.AFS",StringComparison.OrdinalIgnoreCase))??afsFiles.FirstOrDefault()??throw new InvalidDataException("Nenhum AFS foi encontrado na ISO.");var image=AfsService.OpenAfsFromIso(iso!,afsFile);var weapons=AfsService.GetUniqueValidDatEntries(image).Where(x=>WeaponName.IsMatch(x.FileName)).ToArray();return(image,weapons);});
            if(result.weapons.Length==0){summary.Text="Nenhum wepXX.dat encontrado no AFS.";MessageBox.Show(this,"Nenhum pacote wepXX.dat foi encontrado no AFS selecionado.","Armas no AFS",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}
            AfsEntry[] chosen=PickAfsWeapons(result.weapons);if(chosen.Length==0)return;string root=workspaceRoot??Path.GetDirectoryName(iso)!;string? last=null;summary.Text=$"Extraindo {chosen.Length} pacote(s)...";var completed=await Task.Run(()=>{var list=new List<WeaponWorkspacePackage>();foreach(AfsEntry entry in chosen){string packageRoot=Path.Combine(root,"Extracted",Path.GetFileNameWithoutExtension(entry.FileName)),original=Path.Combine(packageRoot,"OriginalDAT",entry.FileName),content=Path.Combine(packageRoot,"Content");AfsService.ExtractEntry(result.image,entry,original);NativeDatService.Extract(original,content);last=Path.Combine(content,entry.FileName);list.Add(new(entry.FileName,original,content));}return (IReadOnlyList<WeaponWorkspacePackage>)list;});packagesExtracted?.Invoke(completed);summary.Text=$"{chosen.Length} pacote(s) extraído(s), registrados e prontos para o Build.";Discover(last);
        }
        catch(Exception ex){summary.Text="Falha ao extrair do AFS.";MessageBox.Show(this,ex.Message,"Extração do AFS",MessageBoxButtons.OK,MessageBoxIcon.Error);}
        finally{UseWaitCursor=false;}
    }
    private AfsEntry[] PickAfsWeapons(AfsEntry[] entries)
    {
        using var dialog=new AppForm {Text="Escolha as armas do AFS",StartPosition=FormStartPosition.CenterParent,ClientSize=new Size(560,560),MinimumSize=new Size(440,400),BackColor=Color.FromArgb(18,20,24),ForeColor=Color.Gainsboro,Font=Font};var list=new CheckedListBox{Dock=DockStyle.Fill,CheckOnClick=true,BackColor=Color.FromArgb(22,25,30),ForeColor=Color.Gainsboro,BorderStyle=BorderStyle.None};var map=new Dictionary<object,AfsEntry>();foreach(AfsEntry entry in entries){object label=WeaponNameCatalog.Display(entry.FileName);list.Items.Add(label);map[label]=entry;}var extract=Button("EXTRAIR MARCADAS",(_,_)=>{if(list.CheckedItems.Count>0)dialog.DialogResult=DialogResult.OK;},160);var all=Button("MARCAR TODAS",(_,_)=>{for(int i=0;i<list.Items.Count;i++)list.SetItemChecked(i,true);},120);var bottom=new FlowLayoutPanel{Dock=DockStyle.Bottom,Height=52,Padding=new Padding(8),FlowDirection=FlowDirection.RightToLeft,BackColor=Color.FromArgb(28,31,37)};bottom.Controls.Add(extract);bottom.Controls.Add(all);dialog.Controls.Add(list);dialog.Controls.Add(bottom);return dialog.ShowLocalizedDialog(this)==DialogResult.OK?list.CheckedItems.Cast<object>().Select(x=>map[x]).ToArray():Array.Empty<AfsEntry>();
    }
    private void MigrateLegacyWeapons()
    {
        if(string.IsNullOrWhiteSpace(workspaceRoot))return;string legacy=Path.Combine(workspaceRoot,"Extracted","Weapons");if(!Directory.Exists(legacy))return;var migrated=new List<WeaponWorkspacePackage>();foreach(string oldDat in Directory.EnumerateFiles(legacy,"wep??.dat",SearchOption.AllDirectories)){try{string name=Path.GetFileName(oldDat),root=Path.Combine(workspaceRoot,"Extracted",Path.GetFileNameWithoutExtension(name)),original=Path.Combine(root,"OriginalDAT",name),content=Path.Combine(root,"Content");if(!File.Exists(original)){Directory.CreateDirectory(Path.GetDirectoryName(original)!);File.Copy(oldDat,original,false);}if(!File.Exists(Path.Combine(content,Path.GetFileNameWithoutExtension(name)+".idx")))NativeDatService.Extract(original,content);migrated.Add(new(name,original,content));}catch{}}if(migrated.Count>0)packagesExtracted?.Invoke(migrated);
    }
    private void LoadPackage()
    {
        models.Items.Clear();testTpl.Items.Clear();if(packages.SelectedItem is not DatItem dat)return;try{DatArchive archive=NativeDatService.Read(dat.Path);int[] tpls=archive.Entries.Where(x=>x.Type.Equals("TPL",StringComparison.OrdinalIgnoreCase)).Select(x=>x.Index).ToArray();testTpl.Items.Add(new TplItem(-1));foreach(int tpl in tpls)testTpl.Items.Add(new TplItem(tpl));foreach(DatEntry entry in archive.Entries.Where(x=>x.Type.Equals("BIN",StringComparison.OrdinalIgnoreCase))){int tpl=ResolveTpl(entry.Index,tpls);int faces=0;try{faces=Ps2ScenarioReader.ReadStandaloneBin(entry.Data).Count;}catch{}var item=new ModelItem(entry.Index,tpl,faces,entry.Data.LongLength);var row=new ListViewItem(item.ToString()){Tag=item};row.SubItems.Add(tpl>=0?$"TPL #{tpl:D3}":"Sem TPL associado");row.SubItems.Add(faces>0?faces.ToString("N0"):"Não renderizável");row.SubItems.Add(FormatSize(entry.Data.LongLength));row.SubItems.Add($"#{entry.Index:D3}");models.Items.Add(row);}summary.Text=$"{WeaponNameCatalog.Display(dat.Path)} • {models.Items.Count} BIN(s) • {tpls.Length} TPL(s)";}catch(Exception ex){summary.Text="Não foi possível ler o DAT";MessageBox.Show(this,ex.Message,"DAT inválido",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
    }
    private static int ResolveTpl(int bin,int[] tpls){if(tpls.Contains(bin+1))return bin+1;int previous=tpls.Where(x=>x<bin).DefaultIfEmpty(-1).Max();if(previous>=0)return previous;return tpls.Where(x=>x>bin).DefaultIfEmpty(-1).Min();}
    private void SyncTplChoice(){if(models.SelectedItems.Count!=1||models.SelectedItems[0].Tag is not ModelItem model)return;for(int i=0;i<testTpl.Items.Count;i++)if(testTpl.Items[i] is TplItem t&&t.Entry==model.Tpl){testTpl.SelectedIndex=i;return;}}
    private void ApplyTplChoice(){if(testTpl.SelectedItem is not TplItem tpl)return;foreach(ListViewItem row in models.SelectedItems){if(row.Tag is not ModelItem model)continue;model.Tpl=tpl.Entry;row.SubItems[1].Text=tpl.Entry<0?"Sem TPL associado":$"TPL #{tpl.Entry:D3}";}}
    private void OpenModels(bool all){if(packages.SelectedItem is not DatItem dat)return;ModelItem[] chosen=(all?models.Items.Cast<ListViewItem>():models.SelectedItems.Cast<ListViewItem>()).Select(x=>(ModelItem)x.Tag!).Where(x=>x.Faces>0).ToArray();if(chosen.Length==0){MessageBox.Show(this,"Selecione ao menos um BIN com geometria reconhecida.","Abrir armas",MessageBoxButtons.OK,MessageBoxIcon.Information);return;}Selection=new(dat.Path,chosen.Select(x=>new WeaponDatPartSelection(x.Bin,x.Tpl)).ToArray());DialogResult=DialogResult.OK;Close();}
    private void Extract(bool all)
    {
        if(packages.SelectedItem is not DatItem dat)return;ModelItem[] chosen=all?models.Items.Cast<ListViewItem>().Select(x=>(ModelItem)x.Tag!).ToArray():models.SelectedItems.Cast<ListViewItem>().Select(x=>(ModelItem)x.Tag!).ToArray();if(chosen.Length==0)return;try{DatArchive archive=NativeDatService.Read(dat.Path);string root=workspaceRoot??Path.GetDirectoryName(dat.Path)!;string destination=Path.Combine(root,"Extracted",Path.GetFileNameWithoutExtension(dat.Path),"Exports");Directory.CreateDirectory(destination);var indices=chosen.SelectMany(x=>x.Tpl>=0?new[]{x.Bin,x.Tpl}:new[]{x.Bin}).Distinct().OrderBy(x=>x);int count=0;foreach(int index in indices){DatEntry entry=archive.Entries[index];string ext=string.IsNullOrWhiteSpace(entry.Type)?"dmy":entry.Type.ToLowerInvariant();File.WriteAllBytes(Path.Combine(destination,$"{Path.GetFileNameWithoutExtension(dat.Path)}_{index:D3}.{ext}"),entry.Data);count++;}summary.Text=$"{count} arquivo(s) exportado(s) em {destination}";MessageBox.Show(this,$"{count} arquivo(s) exportado(s).\n\n{destination}","Exportação concluída",MessageBoxButtons.OK,MessageBoxIcon.Information);}catch(Exception ex){MessageBox.Show(this,ex.Message,"Falha ao exportar",MessageBoxButtons.OK,MessageBoxIcon.Error);}
    }
    private static string FormatSize(long b)=>b<1024?$"{b} B":b<1048576?$"{b/1024d:0.0} KB":$"{b/1048576d:0.0} MB";
}
